// ============================================================================
// 店舗データ（地下階のみ）
// 出典:
//   阪急三番街   https://www.h-sanbangai.com/floor/  各フロア公式マップ（区画番号を目視特定・全152店）
//   ホワイティうめだ https://whity.osaka-chikagai.jp/ 店舗一覧（エリア別・位置調査は進行中）
//   ディアモール大阪 https://www.diamor.jp/about/floor-map/ 公式マップ内SVG座標（全86店・区画番号付き）
// 位置の表現:
//   order: 通り沿いの歩く順 / side: 通路のどちら側（方角） / cell: ホール型フロアの3×3グリッド位置
// ============================================================================

export const SHOP_AREAS = {
  // 阪急三番街（ホール型: 3×3グリッドで配置。rect=[中心mx, 中心my, 幅, 奥行] map px）
  sanban_n_b1: { floor: 'B1', zone: 'sanban', near: ['sanban_n_b1'], rect: [945, 548, 64, 48] },
  sanban_n_b2: { floor: 'B2', zone: 'sanban', near: ['sanban_n_b2'], rect: [945, 548, 64, 48] },
  sanban_s_b1: { floor: 'B1', zone: 'sanban', near: ['sanban_s_b1'], rect: [945, 657, 68, 56] },
  sanban_s_b2: { floor: 'B2', zone: 'sanban', near: ['sanban_s_b2'], rect: [945, 657, 68, 56] },
  // ホワイティうめだ（公式マップSVG座標から並び順・通路側を機械判定・OSM実座標で方位検証済み）
  whity_petit:  { floor: 'B1', zone: 'whity', edges: [['j_pchn', 'opa']] },                       // 南北通路（北→南）
  whity_north1: { floor: 'B1', zone: 'whity', edges: [['j_east1', 'j_nm1s'], ['j_nm1s', 'j_whity_x']] }, // 南北通路
  whity_north2: { floor: 'B1', zone: 'whity', edges: [['j_nm1s', 'j_nm2']] },                     // 阪急東通りへの支通路
  whity_center: { floor: 'B1', zone: 'whity', edges: [['j_metro', 'whity_w'], ['whity_w', 'j_whity_x']] },
  whity_south:  { floor: 'B1', zone: 'whity', edges: [['whity_w', 'j_higashi_n']] },              // 東梅田方面
  whity_east:   { floor: 'B1', zone: 'whity', edges: [['j_whity_x', 'izumi']] },
  whity_nomoka: { floor: 'B1', zone: 'whity', edges: [['izumi', 'izumi_ne']] },
  whity_pocket: { floor: 'B1', zone: 'whity', near: ['j_whity_x'], offset: 5, path: [[1069, 931], [1081, 926]] },
  whity_mikke:  { floor: 'B1', zone: 'whity', near: ['whity_w'], offset: 6, path: [[958, 962], [1042, 962]] },
  whity_faruru: { floor: 'B1', zone: 'whity', near: ['whity_w', 'j_whity_x'], offset: 6, path: [[1005, 920], [1058, 903]] },
  // ディアモール大阪（公式マップSVG座標で全店の並び・側を確認済み 2026-05版）
  diamor_fashion: { floor: 'B1', zone: 'diamor',
    edges: [['j_fashion_w', 'j_diamor_s'], ['j_diamor_s', 'j_fashion_e']] },        // 西→東
  diamor_market: { floor: 'B1', zone: 'diamor', edges: [['enkei', 'j_market_ne']] }, // 広場→北東
  diamor_casual: { floor: 'B1', zone: 'diamor',
    edges: [['j_diamor_n', 'enkei'], ['enkei', 'j_diamor_s']] },                     // 北→南
  diamor_variety: { floor: 'B1', zone: 'diamor',
    edges: [['enkei', 'j_diamor_e'], ['j_diamor_e', 'ekimae4']] },                   // 北西→南東

  // ドーチカ（南北一本道: 西梅田駅南改札→堂島アバンザ）
  dotica: { floor: 'B1', zone: 'dotica', edges: [['j_sone_w', 'dojima'], ['dojima', 'avanza']] },
  // ekimo梅田（御堂筋線コンコース沿い・中改札→南改札）
  ekimo: { floor: 'B1', zone: 'umechika', near: ['j_metro'], offset: 6, path: [[882, 905], [882, 973]] },
  // 大阪駅前第1〜4ビル（ホール型: 3×3グリッド）
  ekimae1_b1: { floor: 'B1', zone: 'ekimae', near: ['ekimae1'], rect: [712, 1307, 92, 56] },
  ekimae1_b2: { floor: 'B2', zone: 'ekimae', near: ['ekimae1_b2'], rect: [712, 1307, 92, 56] },
  ekimae2_b1: { floor: 'B1', zone: 'ekimae', near: ['ekimae2'], rect: [877, 1312, 94, 56] },
  ekimae2_b2: { floor: 'B2', zone: 'ekimae', near: ['ekimae2_b2'], rect: [877, 1312, 94, 56] },
  ekimae3_b1: { floor: 'B1', zone: 'ekimae', near: ['ekimae3'], rect: [1017, 1300, 94, 60] },
  ekimae3_b2: { floor: 'B2', zone: 'ekimae', near: ['ekimae3_b2'], rect: [1017, 1300, 94, 60] },
  ekimae4_b1: { floor: 'B1', zone: 'ekimae', near: ['ekimae4'], rect: [1004, 1197, 88, 56] },
  ekimae4_b2: { floor: 'B2', zone: 'ekimae', near: ['ekimae4_b2'], rect: [1004, 1197, 88, 56] },
  // ルクアB2（バルチカ=東寄り / ルクアフードホール=西寄り）
  barchika: { floor: 'B2', zone: 'osaka_sta', near: ['lucua_b2'], rect: [672, 825, 50, 64] },
  foodhall: { floor: 'B2', zone: 'osaka_sta', near: ['lucua_b2'], rect: [620, 825, 44, 64] },
  // LINKS UMEDA B1（LINKS MARCHE・おいしいもの横丁）
  links_b1: { floor: 'B1', zone: 'osaka_sta', near: ['yodobashi'], rect: [772, 642, 90, 90] },
  // 阪神梅田本店B1 スナックパーク
  snackpark: { floor: 'B1', zone: 'umechika', near: ['hanshin'], rect: [903, 1014, 44, 26] },
  // KITTE大阪B1 うめよこ
  umeyoko: { floor: 'B1', zone: 'osaka_sta', near: ['kitte'], rect: [571, 1019, 72, 78] },
  // うめきた広場B1 UMEKITA CELLAR
  umekita_cellar: { floor: 'B1', zone: 'osaka_sta', near: ['grandfront'], rect: [381, 801, 70, 70] },
  // ヒルトンプラザ（WEST=西棟 / EAST=東棟）
  hilton_west_b1: { floor: 'B1', zone: 'nishi_umeda', near: ['hilton'], rect: [620, 1140, 40, 68] },
  hilton_west_b2: { floor: 'B2', zone: 'nishi_umeda', near: ['hilton_b2'], rect: [620, 1140, 40, 68] },
  hilton_east_b1: { floor: 'B1', zone: 'nishi_umeda', near: ['hilton'], rect: [664, 1140, 40, 68] },
  hilton_east_b2: { floor: 'B2', zone: 'nishi_umeda', near: ['hilton_b2'], rect: [664, 1140, 40, 68] },
  // ハービス（ENT=北棟 / PLAZA(OSAKA)=南棟）
  herbis_ent_b1: { floor: 'B1', zone: 'nishi_umeda', near: ['herbis'], rect: [456, 1234, 120, 52] },
  herbis_ent_b2: { floor: 'B2', zone: 'nishi_umeda', near: ['herbis_b2'], rect: [456, 1234, 120, 52] },
  herbis_plaza_b1: { floor: 'B1', zone: 'nishi_umeda', near: ['herbis'], rect: [456, 1290, 120, 76] },
  herbis_plaza_b2: { floor: 'B2', zone: 'nishi_umeda', near: ['herbis_b2'], rect: [456, 1290, 120, 76] },
};

// 検索用の別表記。店名にキーが含まれていたら候補語を追加
export const ALIASES = {
  'インデアンカレー': ['インディアンカレー', 'インデアン', 'カレー'],
  'マクドナルド': ['マクド', 'まくど', 'mcdonalds'],
  'ミスタードーナツ': ['ミスド', 'ドーナツ'],
  'スターバックス': ['スタバ', 'starbucks'],
  'タリーズ': ['tullys', 'カフェ'],
  'ドトール': ['カフェ'],
  'ゴディバ': ['GODIVA', 'チョコ'],
  'GODIVA': ['ゴディバ', 'チョコ'],
  'いか焼き': ['イカ焼き', 'スナックパーク'],
  '成城石井': ['スーパー'],
  'ファミリーマート': ['ファミマ', 'コンビニ'],
  '旭屋書店': ['本屋', '書店'],
  'サーティワン': ['31', 'アイス'],
  'モスバーガー': ['モス'],
  'フレッシュネスバーガー': ['ハンバーガー'],
  'クリスピー・クリーム': ['ドーナツ'],
  'ムジ コム': ['無印良品', '無印'],
  'キデイランド': ['キディランド', 'おもちゃ'],
};

// 手動配置の店舗（対象3施設の外だが、ランドマークとして重要な店）
export const SHOPS_MANUAL = [
  { name: 'マクドナルド ルクア大阪店', floor: 'B1', mx: 618, my: 842, near: 'lucua', zone: 'osaka_sta' },
  { name: '阪神名物いか焼き (スナックパーク)', floor: 'B1', mx: 902, my: 1012, near: 'hanshin', zone: 'umechika' },
];

// order: 公式マップ上の歩く順 / side: 通路のどちら側か（方角） / cell: 3×3グリッド位置
const s = (name, area, order, side) => ({ name, area, order, side });
const g = (name, area, cell) => ({ name, area, cell });

export const SHOPS_SCRAPED = [
  // ==== 阪急三番街 北館B1F（公式マップ区画順） ====
  g('ニトリ デコホーム', 'sanban_n_b1', '南西'),
  g('フットセラピー', 'sanban_n_b1', '南'),
  g('カードショップ ミント', 'sanban_n_b1', '南東'),
  g('鉄道模型の店 ポポンデッタ', 'sanban_n_b1', '西'),
  g('キデイランド / どんぐり共和国 / スヌーピータウン', 'sanban_n_b1', '中央'),
  g('プリンセスアッシュ', 'sanban_n_b1', '東'),
  g('ウルトラマンワールドM78', 'sanban_n_b1', '東'),
  g('ホロライブプロダクション オフィシャルショップ', 'sanban_n_b1', '東'),
  g('カワチ（画材・文具）', 'sanban_n_b1', '北東'),
  g('ユザワヤ', 'sanban_n_b1', '北西'),
  // ==== 阪急三番街 北館B2F（UMEDA FOOD HALL内） ====
  g('どうとんぼり神座×青藍', 'sanban_n_b2', '北西'),
  g('天丼・天串・串カツ いしのや', 'sanban_n_b2', '北西'),
  g('越南路 エツナンルー', 'sanban_n_b2', '北西'),
  g('お好み焼 清十郎', 'sanban_n_b2', '北西'),
  g('ミアキッチン', 'sanban_n_b2', '北'),
  g('リ:エント楽韓堂', 'sanban_n_b2', '北'),
  g('イタリアンダイニング ペスカ', 'sanban_n_b2', '北'),
  g('&コーヒー メゾンカイザー', 'sanban_n_b2', '中央'),
  g('フレッシュネスバーガー', 'sanban_n_b2', '北東'),
  g('ダパイダン105', 'sanban_n_b2', '東'),
  g('仙台牛たん 麦とろ 三代目文治', 'sanban_n_b2', '東'),
  g('ヨーキーズクレープリー / ピースオブベイク', 'sanban_n_b2', '南東'),
  g('1ポンドのステーキハンバーグ タケル', 'sanban_n_b2', '南'),
  g('みそかつ 矢場とん', 'sanban_n_b2', '南'),
  g('中華そば専門 バラそば屋', 'sanban_n_b2', '南西'),
  g('大阪・堂島 とろ家', 'sanban_n_b2', '南西'),
  g('宮武讃岐うどん', 'sanban_n_b2', '南西'),
  // ==== 阪急三番街 南館B1F（公式マップ区画順） ====
  g('メンディングサービス', 'sanban_s_b1', '南西'),
  g('りそな銀行 セブンデイズプラザ', 'sanban_s_b1', '南西'),
  g('ミッシュマッシュ', 'sanban_s_b1', '南西'),
  g('ハートダンス', 'sanban_s_b1', '南西'),
  g('コスメキッチン', 'sanban_s_b1', '南'),
  g('ミツミネ', 'sanban_s_b1', '南'),
  g('銀座ワシントン', 'sanban_s_b1', '南東'),
  g('ノーリーズソフィー', 'sanban_s_b1', '西'),
  g('コラージュ ガリャルダガランテ', 'sanban_s_b1', '西'),
  g('ロペピクニック 三番街店', 'sanban_s_b1', '西'),
  g('パーフェクトスーツファクトリー', 'sanban_s_b1', '西'),
  g('ディノス F.O.バイ サクラフォークス', 'sanban_s_b1', '西'),
  g('ショップチャンネル大阪', 'sanban_s_b1', '北西'),
  g('カロー', 'sanban_s_b1', '北西'),
  g('ほけんの窓口', 'sanban_s_b1', '北西'),
  g('ロッサ', 'sanban_s_b1', '北西'),
  g('ハーブス 三番街店', 'sanban_s_b1', '中央'),
  g('ユナイテッドアローズ グリーンレーベルリラクシング', 'sanban_s_b1', '中央'),
  g('ピロースタンド', 'sanban_s_b1', '中央'),
  g('スロヴネンヤ ドゥセー', 'sanban_s_b1', '北'),
  g('コキュリコット', 'sanban_s_b1', '北'),
  g('フットデザイン・無重力マッサージ', 'sanban_s_b1', '北'),
  g('ストロベリーフィールズ', 'sanban_s_b1', '東'),
  g('ちいかわらんど', 'sanban_s_b1', '中央'),
  g('ナポカ', 'sanban_s_b1', '中央'),
  g('リーフ', 'sanban_s_b1', '中央'),
  g('ジンズ', 'sanban_s_b1', '北'),
  g('ヘルス＆ビューティー メトラボ', 'sanban_s_b1', '北'),
  g('ポートランド', 'sanban_s_b1', '西'),
  g('モノミュージアム', 'sanban_s_b1', '西'),
  g('フォンテーヌ クチュール', 'sanban_s_b1', '北西'),
  g('ピッコーネ・ローマ', 'sanban_s_b1', '北西'),
  g('チュニック', 'sanban_s_b1', '北西'),
  g('ラフィネ', 'sanban_s_b1', '北西'),
  g('タビインターナショナル', 'sanban_s_b1', '北'),
  g('エメ', 'sanban_s_b1', '東'),
  g('ピーツー ドッグ&キャット', 'sanban_s_b1', '東'),
  g('ビューズ アイブロウ スタジオ', 'sanban_s_b1', '東'),
  g('ファブリック トウキョウ', 'sanban_s_b1', '北東'),
  g('ドライヘッドスパ専門サロン リセット', 'sanban_s_b1', '北東'),
  g('ルージュ・ヴィフ ラクレ', 'sanban_s_b1', '南東'),
  g('プロポーションボディドレッシング', 'sanban_s_b1', '南東'),
  g('ナチュラルビューティーベーシック', 'sanban_s_b1', '東'),
  g('インティミッシミ', 'sanban_s_b1', '東'),
  g('サマンサモスモス', 'sanban_s_b1', '東'),
  g('ハニーズ', 'sanban_s_b1', '東'),
  g('フォルムアイ', 'sanban_s_b1', '北東'),
  g('上島珈琲店', 'sanban_s_b1', '北'),
  g('まねきや', 'sanban_s_b1', '北東'),
  g('鈴乃屋', 'sanban_s_b1', '北東'),
  g('きものやまと', 'sanban_s_b1', '北東'),
  // ==== 阪急三番街 南館B2F（川の流れる街・公式マップ区画順） ====
  g('こなな', 'sanban_s_b2', '南西'),
  g('うを佐', 'sanban_s_b2', '南西'),
  g('家族亭', 'sanban_s_b2', '南'),
  g('生尾', 'sanban_s_b2', '南'),
  g('とんかつKYK', 'sanban_s_b2', '南東'),
  g('ムシベジプラス', 'sanban_s_b2', '南東'),
  g('はまぐり庵 吉祥別邸', 'sanban_s_b2', '南西'),
  g('串かつ料理 活 三番街店', 'sanban_s_b2', '南西'),
  g('海鮮居酒屋あいち 三番街店', 'sanban_s_b2', '南西'),
  g('梅八', 'sanban_s_b2', '西'),
  g('うどん 兎麦', 'sanban_s_b2', '西'),
  g('大同門', 'sanban_s_b2', '西'),
  g('スキヤキフジオ', 'sanban_s_b2', '南西'),
  g('ぼてぢゅう', 'sanban_s_b2', '西'),
  g('インデアンカレー 阪急三番街店', 'sanban_s_b2', '西'),
  g('肉重 ロマン亭', 'sanban_s_b2', '西'),
  g('梅田食堂', 'sanban_s_b2', '西'),
  g('ごはん処 司', 'sanban_s_b2', '西'),
  g('帝塚山 季 TOKI', 'sanban_s_b2', '西'),
  g('グリル ロン', 'sanban_s_b2', '北西'),
  g('祭太鼓', 'sanban_s_b2', '北西'),
  g('マルモキッチン', 'sanban_s_b2', '北西'),
  g('心斎橋ミツヤ 三番街店', 'sanban_s_b2', '北西'),
  g('風流 田毎そば', 'sanban_s_b2', '北西'),
  g('つけめんTETSU', 'sanban_s_b2', '北西'),
  g('上高地 あずさ珈琲', 'sanban_s_b2', '北西'),
  g('ディッパーダン', 'sanban_s_b2', '北'),
  g('リバーカフェ', 'sanban_s_b2', '北'),
  g('スシ海鮮酒場 おか長', 'sanban_s_b2', '北西'),
  g('しゃぶ菜', 'sanban_s_b2', '北'),
  g('御鷹茶屋', 'sanban_s_b2', '北東'),
  g('シルクレーム', 'sanban_s_b2', '南東'),
  g('クワトロナポリ', 'sanban_s_b2', '東'),
  g('パスタ・デ・パスタ', 'sanban_s_b2', '南東'),
  g('とろさば料理専門店 SABAR', 'sanban_s_b2', '東'),
  g('ぶぶ亭', 'sanban_s_b2', '東'),
  g('牛たんとお酒 もりの屋', 'sanban_s_b2', '東'),
  g('ラーメン横綱', 'sanban_s_b2', '北東'),
  g('台湾甜商店', 'sanban_s_b2', '北東'),
  g('昔洋食みつけ亭', 'sanban_s_b2', '北東'),
  g('しのぶ庵', 'sanban_s_b2', '北東'),
  g('雲仙', 'sanban_s_b2', '北東'),
  g('梅蘭', 'sanban_s_b2', '南東'),
  g('梅香 メイシャン', 'sanban_s_b2', '東'),
  g('正起屋 三番街店', 'sanban_s_b2', '東'),
  g('がんこ寿司', 'sanban_s_b2', '東'),
  g('カレーハウス サンマルコ', 'sanban_s_b2', '北東'),
  g('島ぬ風', 'sanban_s_b2', '北東'),
  g('菓匠館 福壽堂秀信', 'sanban_s_b2', '南西'),
  g('はちみつ茶葉園', 'sanban_s_b2', '南西'),
  g('ステラおばさんのクッキー', 'sanban_s_b2', '西'),
  g('神戸・元町 花見屋', 'sanban_s_b2', '西'),
  g('トップス', 'sanban_s_b2', '南'),
  g('茶の彩', 'sanban_s_b2', '中央'),
  g('キッチンキッチン', 'sanban_s_b2', '西'),
  g('モロゾフ', 'sanban_s_b2', '中央'),
  g('喫茶トリコロール', 'sanban_s_b2', '中央'),
  g('宇治園 喫茶去', 'sanban_s_b2', '中央'),
  g('クックハウス 三番街店', 'sanban_s_b2', '東'),
  g('金澤スッポン堂', 'sanban_s_b2', '北'),
  g('マネケン', 'sanban_s_b2', '東'),
  g('茶青花', 'sanban_s_b2', '中央'),
  g('ムーミンカフェスタンド', 'sanban_s_b2', '東'),
  g('ゴディバ 阪急三番街店', 'sanban_s_b2', '東'),
  g('キムラ フルーツパーラー', 'sanban_s_b2', '北'),
  g('アンティコカフェ アルアビス 三番街店', 'sanban_s_b2', '南東'),
  g('サロン ド ロワイヤル', 'sanban_s_b2', '南'),
  g('カフェ バーンホーフ', 'sanban_s_b2', '南'),
  g('デリカKYK', 'sanban_s_b2', '南'),
  g('銀座コージーコーナー', 'sanban_s_b2', '中央'),
  g('手づくり惣菜 咲菜', 'sanban_s_b2', '南'),
  g('大起水産 街のみなと', 'sanban_s_b2', '南'),
  g('成城石井 阪急三番街店', 'sanban_s_b2', '中央'),
  g('べジフルマーケット', 'sanban_s_b2', '南'),
  g('ちひろ菓子店', 'sanban_s_b2', '中央'),
  g('台北餃子張記 三番街店', 'sanban_s_b2', '東'),
  // ==== ホワイティうめだ ノースモール1（北=サニーテラス→南=ポケットパーク方面） ====
  s('ミスタークイックマン 北店', 'whity_north1', 1, '西'),
  s('サーティワンアイスクリーム', 'whity_north1', 2, '西'),
  s('ビアードパパ', 'whity_north1', 3, '西'),
  s('and大阪店', 'whity_north1', 4, '東'),
  s('理容清水', 'whity_north1', 5, '西'),
  s('やきにく萬野', 'whity_north1', 6, '東'),
  s('むさし乃', 'whity_north1', 7, '西'),
  s('海鮮居酒屋あいち', 'whity_north1', 8, '東'),
  s('クックデリ御膳', 'whity_north1', 9, '西'),
  s('赤垣屋', 'whity_north1', 10, '西'),
  s('梅田酒場 すし金', 'whity_north1', 11, '東'),
  s('立呑み処 七津屋', 'whity_north1', 12, '西'),
  s('しゃぶしゃぶぐるまん', 'whity_north1', 13, '東'),
  s('大ざわ', 'whity_north1', 14, '東'),
  s('お好み焼 ゆかり', 'whity_north1', 15, '西'),
  s('中央軒', 'whity_north1', 16, '東'),
  s('地産酒場 十八番', 'whity_north1', 17, '西'),
  s('大阪木津市場 天はな', 'whity_north1', 18, '東'),
  s('きしめんあまの', 'whity_north1', 19, '西'),
  s('正起屋', 'whity_north1', 20, '東'),
  s('ミスタードーナツ ホワイティうめだショップ', 'whity_north1', 21, '西'),
  s('ヨネヤ', 'whity_north1', 22, '西'),
  s('ドトールコーヒーショップ', 'whity_north1', 23, '東'),
  s('串かつ料理 活', 'whity_north1', 24, '西'),
  s('玉乃光酒場 かつお天国', 'whity_north1', 25, '東'),
  s('風流 田舎そば', 'whity_north1', 26, '西'),
  s('直福', 'whity_north1', 27, '東'),
  s('福すし', 'whity_north1', 28, '東'),
  s('タレかつ飯 TSUI TSUI', 'whity_north1', 29, '西'),
  s('じゅろく別邸', 'whity_north1', 30, '東'),
  s('Quark（ロレックス専門店）', 'whity_north1', 31, '西'),
  s('立ち萬', 'whity_north1', 32, '西'),
  s('タリーズコーヒー &TEA', 'whity_north1', 33, '東'),
  s('鳥の巣', 'whity_north1', 34, '西'),
  s('CAFE 英國屋', 'whity_north1', 35, '西'),
  s('夢ステーション うめだ北店', 'whity_north1', 36, '東'),
  s('KIEFEL', 'whity_north1', 37, '西'),
  s('チケット7プレイガイド', 'whity_north1', 38, '西'),
  s('三菱UFJ銀行ATM', 'whity_north1', 39, '西'),
  s('VIE DE FRANCE', 'whity_north1', 40, '東'),
  // ==== ホワイティうめだ ノースモール2（南西→北東=阪急東通り入口） ====
  s('Bechamel Cafe', 'whity_north2', 1, '南東'),
  s('丼丼亭', 'whity_north2', 2, '南東'),
  s('赤白 ホワイティうめだ店', 'whity_north2', 3, '南東'),
  s('堂山食堂', 'whity_north2', 4, '北西'),
  s('串かつだるま', 'whity_north2', 5, '南東'),
  s('すし酒場 さしす', 'whity_north2', 6, '北西'),
  s('油そば きりん寺', 'whity_north2', 7, '南東'),
  s('ウオチカ。', 'whity_north2', 8, '北西'),
  s('牛たん焼き仙台辺見', 'whity_north2', 9, '南東'),
  s('Refresh hands', 'whity_north2', 10, '北西'),
  s('屋台餃子 あらき', 'whity_north2', 11, '南東'),
  // ==== ホワイティうめだ センターモール（西=梅田駅方面→東=ポケットパーク） ====
  s('リンツ ショコラ ブティック', 'whity_center', 1, '北'),
  s('We♡donut×TAKAGI COFFEE', 'whity_center', 2, '南'),
  s('ミスタークイックマン', 'whity_center', 3, '北西'),
  s('conoka（花）', 'whity_center', 4, '北西'),
  s('piccoLo（カレー）', 'whity_center', 5, '北'),
  s('CAFE BREAK', 'whity_center', 6, '南'),
  s('R&K リサイクルキング', 'whity_center', 7, '北'),
  s('セブン銀行ATM センターモール', 'whity_center', 8, '北'),
  s('Afternoon Tea LIVING', 'whity_center', 9, '北'),
  s('心斎橋ミツヤ', 'whity_center', 10, '北'),
  s('Afternoon Tea TEAROOM', 'whity_center', 11, '北'),
  s('ティラミス専門店 リバーレ', 'whity_center', 12, '北'),
  // ==== ホワイティうめだ サウスモール（北西=案内所前→南東=第4ビル/ディアモール方面） ====
  s('夢ステーション うめだ中央店', 'whity_south', 1, '東'),
  s('Miru+（コンタクト）', 'whity_south', 2, '東'),
  s('阪神ドラッグ 梅田地下店', 'whity_south', 3, '東'),
  s('旭屋書店 梅田地下街店', 'whity_south', 4, '東'),
  s('丹青堂', 'whity_south', 5, '西'),
  s('SANRINO（シューズ）', 'whity_south', 6, '東'),
  s('文字の店', 'whity_south', 7, '西'),
  s('花直園芸', 'whity_south', 8, '東'),
  s('買取大吉', 'whity_south', 9, '東'),
  s('セブン銀行ATM サウスモール', 'whity_south', 10, '西'),
  // ==== ホワイティうめだ mikke（西→東・列はunknownの店は交互配置） ====
  s('HIRAMEKI.', 'whity_mikke', 1, '南'),
  s("S'appuyer", 'whity_mikke', 2, '南'),
  s('SENSE OF PLACE by URBAN RESEARCH', 'whity_mikke', 3),
  s('GLACIER lusso', 'whity_mikke', 4, '南'),
  s('Histoire', 'whity_mikke', 5, '北'),
  s('ANIMI MOTIO', 'whity_mikke', 6),
  s('ear PAPILLONNER', 'whity_mikke', 7, '北'),
  s('le VERT', 'whity_mikke', 8, '南'),
  s('&.NOSTALGIA', 'whity_mikke', 9),
  s('tocco closet', 'whity_mikke', 10, '南'),
  s('Lois CRAYON relax', 'whity_mikke', 11),
  s('fitfit', 'whity_mikke', 12, '北'),
  s('inner shop Chelsea', 'whity_mikke', 13, '北'),
  s('tutuanna', 'whity_mikke', 14, '南'),
  s('Shop 無（帽子）', 'whity_mikke', 15),
  s('BE BIRTH 美スギ', 'whity_mikke', 16),
  s('Anker Store', 'whity_mikke', 17, '北'),
  s('Bleu Bleuet', 'whity_mikke', 18),
  // ==== ホワイティうめだ FARURU（南西→北東） ====
  s('Bag select shop fav', 'whity_faruru', 1, '南'),
  s('Zoff ホワイティうめだ店', 'whity_faruru', 2),
  s('fleuve', 'whity_faruru', 3),
  s('DoCLASSE', 'whity_faruru', 4, '南'),
  s('DHC', 'whity_faruru', 5, '西'),
  s('LUSH', 'whity_faruru', 6, '北'),
  s('Via Lattea platino', 'whity_faruru', 7, '南東'),
  s('Via Lattea aurino', 'whity_faruru', 8, '南東'),
  s('眼鏡市場', 'whity_faruru', 9, '北西'),
  s('七宝 SHIPPO', 'whity_faruru', 10, '南東'),
  s('帽子屋Flava', 'whity_faruru', 11, '南東'),
  s('CRAVATTERIA TAM', 'whity_faruru', 12, '南東'),
  s('白牡丹', 'whity_faruru', 13, '南東'),
  s('コクミン FARURU店', 'whity_faruru', 14, '北西'),
  s('REGAL SHOES', 'whity_faruru', 15, '南東'),
  s('Marusho', 'whity_faruru', 16, '南東'),
  // ==== ホワイティうめだ プチシャン（北=Nu茶屋町→南=三番街連絡口） ====
  s('エフワン', 'whity_petit', 1, '東'),
  s('保険クリニック', 'whity_petit', 2, '西'),
  s('MAUA', 'whity_petit', 3, '東'),
  s('あい鍼灸院・接骨院 プチシャン', 'whity_petit', 4, '西'),
  s('和み庵', 'whity_petit', 5, '東'),
  s('B-THREE', 'whity_petit', 6, '西'),
  s('おしゃれ工房＋スマホクリニック', 'whity_petit', 7, '東'),
  s('中古楽器専門店Qsic', 'whity_petit', 8, '西'),
  s('NATURAL KITCHEN', 'whity_petit', 9, '東'),
  s('au Style', 'whity_petit', 10, '西'),
  s('占いの館キセキ', 'whity_petit', 11, '東'),
  s('渡部眼科クリニック', 'whity_petit', 12, '西'),
  s('アイシティ', 'whity_petit', 13, '東'),
  s('Tools（画材・文具）', 'whity_petit', 14, '西'),
  s('美スギ プチシャン店', 'whity_petit', 15, '東'),
  s('BRICK HOUSE シャツ工房', 'whity_petit', 16, '西'),
  s('コクミン プチシャン店', 'whity_petit', 17, '西'),
  s('nooto', 'whity_petit', 18, '東'),
  s('セブン銀行ATM プチシャン', 'whity_petit', 19, '西'),
  // ==== ホワイティうめだ ポケットパーク（広場西〜北西縁） ====
  s('夢ぎゃらりぃハトキン', 'whity_pocket', 1, '西'),
  s('casaneilo', 'whity_pocket', 2, '北'),
  s('クックハウス', 'whity_pocket', 3, '北'),
  // ==== ホワイティうめだ イーストモール（西=ポケットパーク→東=泉の広場） ====
  s('成城石井 ホワイティうめだ店', 'whity_east', 1, '北'),
  s('まるしげ', 'whity_east', 2, '南'),
  s('たこ八', 'whity_east', 3, '北'),
  s('りそな銀行ATM', 'whity_east', 4, '南'),
  s('3COINS', 'whity_east', 5, '北'),
  s('卵と私', 'whity_east', 6, '南'),
  s('リフレッシュハンズ 泉の広場店', 'whity_east', 7, '南'),
  s('コクミン イーストモール店', 'whity_east', 8, '北'),
  s('LUNA EARTH', 'whity_east', 9, '南'),
  s('belle-ville', 'whity_east', 10, '南'),
  s('CAFE 英國屋 NORTH', 'whity_east', 11, '北'),
  s('蕎麦居酒屋 弦', 'whity_east', 12, '南'),
  s('古潭（らーめん）', 'whity_east', 13, '北'),
  s('膳や', 'whity_east', 14, '南'),
  s('うどん王', 'whity_east', 15, '南'),
  s('WithGreen ホワイティうめだ店', 'whity_east', 16, '北'),
  s('大阪トンテキ', 'whity_east', 17, '南'),
  s('大起水産 回転寿司', 'whity_east', 18, '北'),
  s('洋麺屋 五右衛門', 'whity_east', 19, '南'),
  s('大阪炒飯倶楽部', 'whity_east', 20, '南'),
  s('騒豆花', 'whity_east', 21, '北'),
  s('セブン銀行ATM イーストモール', 'whity_east', 22, '南'),
  s('ごちとん（豚汁定食）', 'whity_east', 23, '北'),
  s('新潟をこめ', 'whity_east', 24, '南'),
  s('モスバーガー ホワイティうめだ店', 'whity_east', 25, '北'),
  s('甘党まえだ', 'whity_east', 26, '北'),
  s('スターバックスコーヒー ホワイティうめだ店', 'whity_east', 27, '南'),
  s('ブルーレモン #CHIKAMISE', 'whity_east', 28, '西'),
  s('炙り肉寿司 コマツバラファーム', 'whity_east', 29, '北'),
  // ==== ホワイティうめだ NOMOKA（南=泉の広場→北=中崎町方面） ====
  s('もんじゃのえびせん', 'whity_nomoka', 1, '東'),
  s('CRAFT BEER MARKET', 'whity_nomoka', 2, '西'),
  s('台北餃子張記', 'whity_nomoka', 3, '西'),
  s('イタリアン魚酒場アルバータ', 'whity_nomoka', 4, '東'),
  s('京の串揚げ 祇園囃子', 'whity_nomoka', 5, '東'),
  s('川北商店（焼鳥）', 'whity_nomoka', 6, '西'),
  s('YEBISU BAR', 'whity_nomoka', 7, '東'),
  s('博多 天神ホルモン', 'whity_nomoka', 8, '西'),
  s('ミアスタンド', 'whity_nomoka', 9, '東'),
  s('わすれな草', 'whity_nomoka', 10, '東'),
  s('浪花ハイボール', 'whity_nomoka', 11, '東'),
  s('沖縄酒場あしびなー', 'whity_nomoka', 12, '西'),
  s('鮨酒場てっぺい', 'whity_nomoka', 13, '東'),
  s('韓国酒場コッキオ', 'whity_nomoka', 14, '西'),
  s('天ぷら大吉', 'whity_nomoka', 15, '東'),
  s('漁師酒場 あらき', 'whity_nomoka', 16, '西'),
  s('徳田酒店', 'whity_nomoka', 17, '西'),
  // ==== ディアモール大阪 ファッショナブルストリート（西→東・公式マップ準拠） ====
  s('フレームワーク', 'diamor_fashion', 1),
  s('LAKOLE', 'diamor_fashion', 2),
  s('ビス', 'diamor_fashion', 3),
  s('ブーレ', 'diamor_fashion', 4, '北'),
  s('デシグアル', 'diamor_fashion', 5, '南'),
  s('WithGreen ディアモール店', 'diamor_fashion', 6, '北'),
  s('卑弥呼', 'diamor_fashion', 7, '南'),
  s('ムジ コム（無印良品）', 'diamor_fashion', 8, '北'),
  s('ITAL STYLE', 'diamor_fashion', 9, '南'),
  s('ロペピクニック ディアモール店', 'diamor_fashion', 10, '北'),
  s('パラスパレス', 'diamor_fashion', 11, '南'),
  s('GINZA Global Style', 'diamor_fashion', 12, '北'),
  s('大阪市梅田サービスカウンター', 'diamor_fashion', 13, '北'),
  s('DoCLASSE メンズ店', 'diamor_fashion', 14, '南'),
  s('アンティコカフェ アルアビス', 'diamor_fashion', 15, '南'),
  s('ケユカ', 'diamor_fashion', 16, '北'),
  s('ハーブス ディアモール店', 'diamor_fashion', 17, '南'),
  s('ダイアナ', 'diamor_fashion', 18, '北'),
  s('TEA18', 'diamor_fashion', 19, '南'),
  s('SUBWAY', 'diamor_fashion', 20, '南'),
  s('ムシベジプラスカフェ', 'diamor_fashion', 21, '北'),
  s('サンマルクカフェ', 'diamor_fashion', 22, '北'),
  s('TO THE HERBS', 'diamor_fashion', 23, '南'),
  s('ワタナベ眼科', 'diamor_fashion', 24, '北'),
  s('ファミリーマート ファッショナブルストリート店', 'diamor_fashion', 25, '北'),
  s('ZETTERIA', 'diamor_fashion', 26, '南'),
  s('そじ坊', 'diamor_fashion', 27, '北'),
  // ==== ディアモール大阪 マーケットストリート（円形広場→北東・公式マップ準拠） ====
  s('ピエール・エルメ・パリ', 'diamor_market', 1, '北西'),
  s('ヴェンキ', 'diamor_market', 2, '南東'),
  s('クリスピー・クリーム・ドーナツ', 'diamor_market', 3, '南東'),
  s('タリーズコーヒー ディアモール大阪', 'diamor_market', 4, '北西'),
  s('ゆうちょ銀行ATM', 'diamor_market', 5, '南東'),
  s('アモスタイル バイ トリンプ', 'diamor_market', 6, '北西'),
  s('COFFEE STYLE UCC', 'diamor_market', 7, '南東'),
  s('サルート by ワコール', 'diamor_market', 8, '北西'),
  s('atelier haruka', 'diamor_market', 9, '南東'),
  s('フットデザイン ディアモール店', 'diamor_market', 10, '北西'),
  s('美スギ・コスメガーデンS', 'diamor_market', 11, '南東'),
  s('aiicosme', 'diamor_market', 12, '南東'),
  s('美スギ・コスメガーデン', 'diamor_market', 13, '北西'),
  s('久世福商店 ディアモール店', 'diamor_market', 14, '南東'),
  s('美スギ・SK-II', 'diamor_market', 15, '北西'),
  s('クイーンズウェイ ディアモール店', 'diamor_market', 16, '南東'),
  s('UQスポット', 'diamor_market', 17, '北西'),
  s('ドトールコーヒーショップ ディアモール店', 'diamor_market', 18, '南東'),
  s('サーティワンアイスクリーム ディアモール店', 'diamor_market', 19, '北西'),
  s('ジンズ ディアモール店', 'diamor_market', 20, '北西'),
  s('ファミリーマート マーケットストリート店', 'diamor_market', 21, '南東'),
  s('保険クリニック ディアモール店', 'diamor_market', 22, '北西'),
  s('青山フラワーマーケット', 'diamor_market', 23, '南東'),
  // ==== ディアモール大阪 カジュアルストリート（北=阪神側→円形広場→南=堂島方面） ====
  s('三井住友銀行ATM', 'diamor_casual', 1, '東'),
  s('ルクールブラン', 'diamor_casual', 2, '西'),
  s('チャールズ & キース', 'diamor_casual', 3, '東'),
  s('楽天モバイル ディアモール大阪', 'diamor_casual', 4, '西'),
  s('セブン銀行ATM ディアモール', 'diamor_casual', 5, '西'),
  s('GODIVA café DIAMOR OSAKA', 'diamor_casual', 6, '西'),
  s('CocoLe by le-noble', 'diamor_casual', 7, '東'),
  s('DIAMOR and.', 'diamor_casual', 8, '西'),
  s('12 Twelve Agenda', 'diamor_casual', 9, '西'),
  s('アーバンリサーチ ロッソ', 'diamor_casual', 10, '西'),
  s('ストラ', 'diamor_casual', 11, '西'),
  s('YECCA VECCA', 'diamor_casual', 12, '西'),
  s('Jil Purple', 'diamor_casual', 13, '西'),
  s('テチチ', 'diamor_casual', 14, '西'),
  s('ミスターミニット', 'diamor_casual', 15, '東'),
  s('KASHIYAMA', 'diamor_casual', 16, '西'),
  s('リフレッシュハンズ ディアモール店', 'diamor_casual', 17, '西'),
  s('りそな・関西みらい銀行ATM', 'diamor_casual', 18, '東'),
  // ==== ディアモール大阪 バラエティストリート（円形広場→南東・公式マップ準拠） ====
  s('コクミン ディアモール店', 'diamor_variety', 1, '北東'),
  s('ショップイン', 'diamor_variety', 2, '北東'),
  s('チュチュアンナ ディアモール店', 'diamor_variety', 3, '北東'),
  s('グレディブリリアン ディアモール店', 'diamor_variety', 4, '北東'),
  s('ACE BAGS&LUGGAGE', 'diamor_variety', 5, '北東'),
  s('Histoire ディアモール店', 'diamor_variety', 6, '南西'),
  s('オリヒカ', 'diamor_variety', 7, '北東'),
  s('ランダ', 'diamor_variety', 8, '南西'),
  s('ATELIER ALBION', 'diamor_variety', 9, '北東'),
  s('LIB（レザーグッズ）', 'diamor_variety', 10, '南西'),
  s('サマンサモスモス ディアモール店', 'diamor_variety', 11, '北東'),
  s('ゾフ ディアモール店', 'diamor_variety', 12, '南西'),
  s('クリア', 'diamor_variety', 13, '北東'),
  s('ハートダンス ディアモール店', 'diamor_variety', 14, '北東'),
  s('ダブリューダブリューエス', 'diamor_variety', 15, '南西'),
  s('コキュリコット ディアモール店', 'diamor_variety', 16, '北東'),
  s('ディアモールチャンスセンター（宝くじ）', 'diamor_variety', 17, '北東'),
  s('ドコモショップ', 'diamor_variety', 18, '西'),
  // ==== ドーチカ（公式マップ区画番号を突合・北端→南端の通し順・全53店 2026-07） ====
  s('三菱UFJ銀行ATM', 'dotica', 1, '西'),
  s('新梅田コクミン薬局', 'dotica', 2, '東'),
  s('KIEFEL COFFEE', 'dotica', 3, '西'),
  s('ファミリーマート ドーチカ店', 'dotica', 4, '東'),
  s('plus on ドーチカ店', 'dotica', 5, '西'),
  s('レオニダス 大阪梅田店', 'dotica', 6, '西'),
  s('インデアンカレー 堂島店', 'dotica', 7, '東'),
  s('東京油組総本店 ドーチカ組', 'dotica', 8, '西'),
  s('newKOBE 堂島店', 'dotica', 9, '東'),
  s('わたしのダイニング × SAKAGURA', 'dotica', 10, '西'),
  s('みずほ銀行ATM', 'dotica', 11, '東'),
  s('ダル食堂 堂島地下街店', 'dotica', 12, '西'),
  s('ミスタークイックマン', 'dotica', 13, '東'),
  s('りそな銀行ATM', 'dotica', 14, '東'),
  s('コクミンドラッグ ドーチカ店', 'dotica', 15, '西'),
  s('ほけん百花 梅田ドーチカ店', 'dotica', 16, '東'),
  s('J・マーケット大阪ドーチカ店', 'dotica', 17, '東'),
  s('文字の店 堂島', 'dotica', 18, '西'),
  s('じゃんぱら大阪堂島店', 'dotica', 19, '東'),
  s('BIG VISION', 'dotica', 20, '西'),
  s('中央コンタクト', 'dotica', 21, '西'),
  s('コクミンドラッグ 堂島店', 'dotica', 22, '東'),
  s('ちぐさ大阪うめだ支店', 'dotica', 23, '西'),
  s('リフレッシュ工房オズ 堂島店', 'dotica', 24, '西'),
  s('セブン銀行ATM', 'dotica', 25, '東'),
  s('時計修理工房 白金堂 大阪梅田ドーチカ店', 'dotica', 26, '西'),
  s('西梅田眼科クリニック', 'dotica', 27, '東'),
  s('青森・岩手えぇもんショップ', 'dotica', 28, '西'),
  s('TRARIUM by ACE', 'dotica', 29, '東'),
  s('Buena.', 'dotica', 30, '西'),
  s('KENFORD堂島地下街店', 'dotica', 31, '東'),
  s('梅田もりわき骨盤鍼灸整骨院', 'dotica', 32, '西'),
  s('千鳥屋宗家 堂島店', 'dotica', 33, '東'),
  s('Perfect Suit FActory', 'dotica', 34, '西'),
  s('ダイソー', 'dotica', 35, '西'),
  s('クックデリ御膳 ドーチカ店', 'dotica', 36, '東'),
  s('三井住友銀行ATM', 'dotica', 37, '西'),
  s('ドトールコーヒーショップドーチカ', 'dotica', 38, '東'),
  s('おたからや梅田ドーチカ店', 'dotica', 39, '西'),
  s('KUSELESS', 'dotica', 40, '西'),
  s('吉野家', 'dotica', 41, '西'),
  s('都由堂島店', 'dotica', 42, '東'),
  s('かっぽうぎ ドーチカ店', 'dotica', 43, '西'),
  s('Barber the GM 堂島', 'dotica', 44, '東'),
  s('おきがる串家物語', 'dotica', 45, '西'),
  s('お酒の美術館 ドーチカ店', 'dotica', 46, '東'),
  s('おらが蕎麦', 'dotica', 47, '西'),
  s('ドットミーティング堂島貸会議室', 'dotica', 48, '東'),
  s('海鮮居酒屋あいち', 'dotica', 49, '西'),
  s('中央軒 ドーチカ店', 'dotica', 50, '東'),
  s('つけ麺専門店 三田製麺所 ドーチカ店', 'dotica', 51, '西'),
  s('CAFÉ ONthe', 'dotica', 52, '西'),
  s('自家製麺杵屋', 'dotica', 53, '東'),
  // ==== ルクアB2 バルチカ（公式マップ2026-06版・N=上確認済み・全26店） ====
  g('焼肉トラジ', 'barchika', '北西'),
  g('創業明治23年 徳田酒店', 'barchika', '北西'),
  g('韓国酒場 コッキオ', 'barchika', '北西'),
  g('炭火焼鳥 権兵衛', 'barchika', '北西'),
  g('あべの たこやき やまちゃん', 'barchika', '西'),
  g('となりのジャックとマチルダ', 'barchika', '西'),
  g('やきにく 萬野', 'barchika', '西'),
  g('松葉', 'barchika', '中央'),
  g('オステリア・ガウダンテ', 'barchika', '中央'),
  g('梅田麹室 豊祝', 'barchika', '中央'),
  g('旧ヤム鐵道', 'barchika', '東'),
  g('鮨ト酒 日々晴々', 'barchika', '東'),
  g('ハモネリア ベジョータ ギョクロ', 'barchika', '東'),
  g('フレンチおでん「赤白」コウハク', 'barchika', '東'),
  g('うなぎ 串焼き いづも', 'barchika', '南西'),
  g('魚屋スタンドふじ子', 'barchika', '南西'),
  g('チャイニーズ ビストロ 蘭亭', 'barchika', '南西'),
  g('クラフトビアマーケット', 'barchika', '南西'),
  g('銀座 篝', 'barchika', '南'),
  g('タイ国政府認定三ツ星レストラン クンテープ', 'barchika', '南'),
  g('本町製麺所 天', 'barchika', '南'),
  g('お好み たまちゃん', 'barchika', '南'),
  g('もつ焼ウッチャン', 'barchika', '南'),
  g('羽根つき焼小籠包 鼎\'s（Din\'s）', 'barchika', '南東'),
  g('人類みな麺類Premium', 'barchika', '南東'),
  g('宮崎酒場 ゑびす', 'barchika', '南東'),
  // ==== ルクアB2 ルクアフードホール（同上・全15店） ====
  g('キッチン＆マーケット', 'foodhall', '北西'),
  g('スターバックス（リザーブバー）', 'foodhall', '北東'),
  g('北摂スパイス研究所', 'foodhall', '中央'),
  g('串やき まんてん', 'foodhall', '中央'),
  g('サーティワンアイスクリーム', 'foodhall', '東'),
  g('ミャムミャム', 'foodhall', '東'),
  g('クリスピー・クリーム・ドーナツ', 'foodhall', '東'),
  g('ゴンチャ', 'foodhall', '東'),
  g('築地食堂 源ちゃん', 'foodhall', '南'),
  g('とんかつ 新宿さぼてん', 'foodhall', '南'),
  g('マルトメ・ザ・ジューサリー パフェテリア', 'foodhall', '南東'),
  g('北極星', 'foodhall', '南東'),
  g('クア・アイナ', 'foodhall', '南東'),
  g('だし茶漬け+肉うどん えん', 'foodhall', '南東'),
  g('ビフテキ重・肉飯 ロマン亭', 'foodhall', '南東'),
  // ==== ekimo梅田（中南改札→南改札の並び順・全12店） ====
  s('J・マーケット', 'ekimo', 1, '東'),
  s('オーエスドラッグ', 'ekimo', 2, '東'),
  s('ノムラクリーニング', 'ekimo', 3, '西'),
  s('LUNA EARTH', 'ekimo', 4, '東'),
  s('MUJI com', 'ekimo', 5, '西'),
  s('karendo', 'ekimo', 6, '東'),
  s('UNIQLO', 'ekimo', 7, '西'),
  s('メガネスーパーコンタクト', 'ekimo', 8, '東'),
  s('JINS', 'ekimo', 9, '西'),
  s('三井住友銀行ATMコーナー', 'ekimo', 10, '西'),
  s('ミスタードーナツ', 'ekimo', 11, '東'),
  s('八天堂', 'ekimo', 12, '東'),
];
