// ============================================================================
// 店舗データ（地下階のみ）
// 出典:
//   阪急三番街   https://www.h-sanbangai.com/floor/  各フロア公式マップ（区画番号を目視特定・全152店）
//   ホワイティうめだ https://whity.osaka-chikagai.jp/ 店舗一覧（エリア別・位置調査は進行中）
//   ディアモール大阪 https://www.diamor.jp/about/floor-map/ 公式マップ内SVG座標（全86店・区画番号付き）
// 位置の表現:
//   order: 通り沿いの歩く順 / side: 通路のどちら側（方角） / cell: ホール型フロアの3×3グリッド位置
// ============================================================================

export const SHOP_AREAS = {
  // 阪急三番街（ホール型: 3×3グリッドで配置。rect=[中心mx, 中心my, 幅, 奥行] メートル）
  // merged: 店舗の形状は将来対応。それまで個別ドットは描かず館ごとに1点へ集約(検索・ルート案内はそのまま)
  sanban_n_b1: { floor: 'S1', zone: 'sanban', near: ['sanban_n_b1'], rect: [950, 520, 70, 42], merged: true }, // 北館B1F=浅層
  sanban_n_b2: { floor: 'B1', zone: 'sanban', near: ['sanban_n_b2'], rect: [950, 520, 70, 42], merged: true }, // 北館B2F=中枢層
  sanban_s_b1: { floor: 'S1', zone: 'sanban', near: ['sanban_s_b1'], rect: [973, 682.8, 75.3, 49.9], merged: true }, // 南館B1F=浅層
  sanban_s_b2: { floor: 'B1', zone: 'sanban', near: ['sanban_s_b2'], rect: [973, 682.8, 75.3, 49.9], merged: true }, // 南館B2F=中枢層
  // ホワイティうめだ（公式マップSVG座標から並び順・通路側を機械判定・OSM実座標で方位検証済み）
  whity_petit:  { floor: 'B1', zone: 'whity', edges: [['j_pchn', 'opa']] },                       // 南北通路（北→南）
  whity_north1: { floor: 'B1', zone: 'whity', edges: [['j_east1', 'whity_37'], ['whity_37', 'whity_35'], ['whity_35', 'whity_34'], ['whity_34', 'whity_31'], ['whity_31', 'whity_32'], ['whity_32', 'j_whity_x']] }, // 南北通路
  whity_north2: { floor: 'B1', zone: 'whity', edges: [['j_nm1s', 'j_nm2']] },                     // 阪急東通りへの支通路
  whity_center: { floor: 'B1', zone: 'whity', edges: [['j_metro', 'whity_w'], ['whity_w', 'whity_13'], ['whity_13', 'whity_14'], ['whity_14', 'whity_30'], ['whity_30', 'whity_32'], ['whity_32', 'j_whity_x']] },
  whity_south:  { floor: 'B1', zone: 'whity', edges: [['whity_w', 'whity_13'], ['whity_13', 'whity_14'], ['whity_14', 'whity_30'], ['whity_30', 'j_higashi_n']] },              // 東梅田方面
  whity_east:   { floor: 'B1', zone: 'whity', edges: [['j_whity_x', 'whity_32'], ['whity_32', 'whity_30'], ['whity_30', 'whity_40'], ['whity_40', 'izumi']] },
  whity_nomoka: { floor: 'B1', zone: 'whity', edges: [['izumi', 'whity_40'], ['whity_40', 'izumi_ne']] },
  whity_pocket: { floor: 'B1', zone: 'whity', near: ['j_whity_x'], offset: 5, path: [[1093.8, 946.9], [1107.2, 946.2]] },
  whity_mikke:  { floor: 'B1', zone: 'whity', near: ['whity_w'], edges: [['whity_07', 'whity_02'], ['whity_02', 'whity_03'], ['whity_03', 'whity_14'], ['whity_14', 'whity_30']] },
  whity_faruru: { floor: 'B1', zone: 'whity', near: ['whity_w', 'j_whity_x'], edges: [['whity_22', 'whity_23'], ['whity_23', 'whity_31'], ['whity_31', 'whity_32'], ['whity_32', 'j_whity_x']] },
  // ディアモール大阪（公式マップSVG座標で全店の並び・側を確認済み 2026-05版）
  diamor_fashion: { floor: 'B1', zone: 'diamor', edges: [['j_fashion_w', 'j_diamor_s'], ['j_diamor_s', 'j_diamor_e'], ['j_diamor_e', 'j_fashion_e']] },        // 西→東
  diamor_market: { floor: 'B1', zone: 'diamor', edges: [['enkei', 'diamor_03'], ['diamor_03', 'j_market_ne']] }, // 広場→北東
  diamor_casual: { floor: 'B1', zone: 'diamor', edges: [['j_diamor_n', 'enkei'], ['enkei', 'diamor_03'], ['diamor_03', 'j_diamor_s']] },                     // 北→南
  diamor_variety: { floor: 'B1', zone: 'diamor', edges: [['enkei', 'diamor_03'], ['diamor_03', 'diamor_04'], ['diamor_04', 'j_variety'], ['j_variety', 'j_diamor_e']] },  // バラエティST本通り(OSMカーブ追従)。第4ビルへの枝には店を置かない

  // ドーチカ（南北一本道: 西梅田駅南改札→堂島アバンザ）
  dotica: { floor: 'B1', zone: 'dotica', edges: [['j_sone_w', 'dojima'], ['dojima', 'dotica_01'], ['dotica_01', 'avanza']] },
  // ekimo梅田（御堂筋線コンコース沿い・中改札→南改札）
  ekimo: { floor: 'B1', zone: 'umechika', near: ['j_metro'], edges: [['j_metro', 'umechika_15'], ['umechika_15', 'umechika_11']] },
  // 大阪駅前第1〜4ビル（ホール型: 3×3グリッド）
  ekimae1_b1: { floor: 'S1', zone: 'ekimae', near: ['ekimae1'], rect: [771, 1287.1, 94.2, 57.9] },
  ekimae1_b2: { floor: 'B1', zone: 'ekimae', near: ['ekimae1_b2'], rect: [793.2, 1286.3, 104.1, 64.1] },
  ekimae2_b1: { floor: 'S1', zone: 'ekimae', near: ['ekimae2'], rect: [907.1, 1312.6, 55.4, 34.7] },
  ekimae2_b2: { floor: 'B1', zone: 'ekimae', near: ['ekimae2_b2'], rect: [931, 1297.5, 93.1, 72.2] },
  ekimae3_b1: { floor: 'S1', zone: 'ekimae', near: ['ekimae3'], rect: [1053.1, 1298.5, 93.1, 72.2] },
  ekimae3_b2: { floor: 'B1', zone: 'ekimae', near: ['ekimae3_b2'], rect: [1053.1, 1298.5, 93.1, 72.2] },
  ekimae4_b1: { floor: 'S1', zone: 'ekimae', near: ['ekimae4'], rect: [987.9, 1169.8, 57.6, 25.8] },
  ekimae4_b2: { floor: 'B1', zone: 'ekimae', near: ['ekimae4_b2'], rect: [1013.6, 1177.8, 95.3, 61.5] },
  // ルクアB2（バルチカ=東寄り / ルクアフードホール=西寄り）
  barchika: { floor: 'B1', zone: 'lucua', near: ['lucua_b2'], rect: [726.9, 819.8, 55.4, 57] }, // ルクアB2F=中枢層
  foodhall: { floor: 'B1', zone: 'lucua', near: ['lucua_b2'], rect: [678.7, 839.4, 48.8, 57] }, // ルクアB2F=中枢層
  // LINKS UMEDA B1（LINKS MARCHE・おいしいもの横丁）
  links_b1: { floor: 'S1', zone: 'links', near: ['yodobashi'], rect: [773.5, 684.5, 123, 112.3] }, // リンクスB1F=浅層
  // 阪神梅田本店B1 スナックパーク
  snackpark: { floor: 'B1', zone: 'hanshin_dept', near: ['hanshin'], rect: [914.5, 1028.9, 34.3, 16] },
  // KITTE大阪B1 うめよこ
  umeyoko: { floor: 'B1', zone: 'kitte', near: ['kitte'], rect: [567.9, 1112.4, 65.4, 71.3] },
  // うめきた広場B1 UMEKITA CELLAR
  umekita_cellar: { floor: 'S1', zone: 'grandfront', near: ['grandfront'], rect: [647.4, 695.2, 77.6, 62.4] }, // 北西クラスタ=浅層
  // イーマ(E-MA)。地下接続はB1のみなので全館の店を1エリアに集約(merged=1点表示)。cellは館内フロア別の目安
  ema_all: { floor: 'B1', zone: 'ema', near: ['ema'], rect: [983, 1099, 24, 40], merged: true },
  // ヒルトンプラザ（WEST=西棟 / EAST=東棟）
  hilton_west_b1: { floor: 'B1', zone: 'hilton', near: ['hilton'], rect: [680, 1182.4, 37.7, 55.2] },
  hilton_west_b2: { floor: 'B2', zone: 'hilton', near: ['hilton_b2'], rect: [680, 1182.4, 37.7, 55.2] },
  hilton_east_b1: { floor: 'B1', zone: 'hilton', near: ['hilton'], rect: [772.2, 1153.3, 49.9, 78.4] },
  hilton_east_b2: { floor: 'B2', zone: 'hilton', near: ['hilton_b2'], rect: [776.6, 1153.2, 62, 98] },
  // ハービス（ENT=北棟 / PLAZA(OSAKA)=南棟）
  herbis_ent_b1: { floor: 'B1', zone: 'herbis', near: ['herbis'], rect: [632.9, 1202.8, 82, 69.5] },
  herbis_ent_b2: { floor: 'B2', zone: 'herbis', near: ['herbis_b2'], rect: [619.4, 1196.2, 82, 69.5] },
  herbis_plaza_b1: { floor: 'B1', zone: 'herbis', near: ['herbis'], rect: [438.3, 1356.8, 46.5, 51.7] },
  herbis_plaza_b2: { floor: 'B2', zone: 'herbis', near: ['herbis_b2'], rect: [451.3, 1344.7, 46.5, 58.8] },
};

// 検索用の別表記。店名にキーが含まれていたら候補語を追加
export const ALIASES = {
  'インデアンカレー': ['インディアンカレー', 'インデアン', 'カレー'],
  'マクドナルド': ['マクド', 'まくど', 'mcdonalds'],
  'ミスタードーナツ': ['ミスド', 'ドーナツ'],
  'スターバックス': ['スタバ', 'starbucks'],
  'タリーズ': ['tullys', 'カフェ'],
  'ドトール': ['カフェ'],
  'ゴディバ': ['GODIVA', 'チョコ'],
  'GODIVA': ['ゴディバ', 'チョコ'],
  'いか焼き': ['イカ焼き', 'スナックパーク'],
  '成城石井': ['スーパー'],
  'ファミリーマート': ['ファミマ', 'コンビニ'],
  '旭屋書店': ['本屋', '書店'],
  'サーティワン': ['31', 'アイス'],
  'モスバーガー': ['モス'],
  'フレッシュネスバーガー': ['ハンバーガー'],
  'クリスピー・クリーム': ['ドーナツ'],
  'ムジ コム': ['無印良品', '無印'],
  'キデイランド': ['キディランド', 'おもちゃ'],
};

// 手動配置の店舗（対象3施設の外だが、ランドマークとして重要な店）
export const SHOPS_MANUAL = [
  { name: 'マクドナルド ルクア大阪店', floor: 'B1', mx: 677.0, my: 854.6, near: 'lucua', zone: 'lucua' },
  // 百貨店は「1フロア=1店」で登録(デパ地下カウンター個別収録はしない方針・2026-07相談で決定)
  { name: '大丸梅田店 B1F(デパ地下)',        floor: 'B1', mx: 796.5, my: 982.2, near: 'daimaru',      zone: 'daimaru' },
  { name: '大丸梅田店 B2F(食品・ベーカリー)', floor: 'B2', mx: 783.7, my: 996.1, near: 'j_daimaru_b2', zone: 'daimaru' },
  { name: '阪急うめだ本店 B1F(デパ地下)',     floor: 'B1', mx: 1002.9, my: 850.2, near: 'hankyu_dept',  zone: 'hankyu_dept' },
  { name: '阪急うめだ本店 B2F(生鮮・惣菜)',   floor: 'B2', mx: 987.1, my: 874.8, near: 'j_hankyu_b2', zone: 'hankyu_dept' },
  { name: '阪神梅田本店 B1F(食品館)',         floor: 'B1', mx: 942.7, my: 1043.9, near: 'hanshin',      zone: 'hanshin_dept' },
  { name: '堂島アバンザ B1F(レストラン街)',   floor: 'B1', mx: 785.7, my: 1499.6, near: 'j_avz',        zone: 'avanza' },
  { name: '阪神梅田本店 B2F(阪神バル横丁)',   floor: 'B2', mx: 934.0, my: 1049.6, near: 'hanshin_home', zone: 'hanshin_dept' },
  { name: '梅田メンタルクリニック', floor: 'B1', mx: 235.8, my: 1435.4, near: 'exit_6_1', zone: 'nishi_umeda' }, // 出口6-1のすぐ横(現地確認 2026-08-23)
];

// order: 公式マップ上の歩く順 / side: 通路のどちら側か（方角） / cell: 3×3グリッド位置
const s = (name, area, order, side) => ({ name, area, order, side });
const g = (name, area, cell) => ({ name, area, cell });

export const SHOPS_SCRAPED = [
  // ==== 阪急三番街 北館B1F（公式マップ区画順） ====
  g('ニトリ デコホーム', 'sanban_n_b1', '南西'),
  g('フットセラピー', 'sanban_n_b1', '南'),
  g('カードショップ ミント', 'sanban_n_b1', '南東'),
  g('鉄道模型の店 ポポンデッタ', 'sanban_n_b1', '西'),
  g('キデイランド / どんぐり共和国 / スヌーピータウン', 'sanban_n_b1', '中央'),
  g('プリンセスアッシュ', 'sanban_n_b1', '東'),
  g('ウルトラマンワールドM78', 'sanban_n_b1', '東'),
  g('ホロライブプロダクション オフィシャルショップ', 'sanban_n_b1', '東'),
  g('カワチ（画材・文具）', 'sanban_n_b1', '北東'),
  g('ユザワヤ', 'sanban_n_b1', '北西'),
  // ==== 阪急三番街 北館B2F（UMEDA FOOD HALL内） ====
  g('どうとんぼり神座×青藍', 'sanban_n_b2', '北西'),
  g('天丼・天串・串カツ いしのや', 'sanban_n_b2', '北西'),
  g('越南路 エツナンルー', 'sanban_n_b2', '北西'),
  g('お好み焼 清十郎', 'sanban_n_b2', '北西'),
  g('ミアキッチン', 'sanban_n_b2', '北'),
  g('リ:エント楽韓堂', 'sanban_n_b2', '北'),
  g('イタリアンダイニング ペスカ', 'sanban_n_b2', '北'),
  g('&コーヒー メゾンカイザー', 'sanban_n_b2', '中央'),
  g('フレッシュネスバーガー', 'sanban_n_b2', '北東'),
  g('ダパイダン105', 'sanban_n_b2', '東'),
  g('仙台牛たん 麦とろ 三代目文治', 'sanban_n_b2', '東'),
  g('ヨーキーズクレープリー / ピースオブベイク', 'sanban_n_b2', '南東'),
  g('1ポンドのステーキハンバーグ タケル', 'sanban_n_b2', '南'),
  g('みそかつ 矢場とん', 'sanban_n_b2', '南'),
  g('中華そば専門 バラそば屋', 'sanban_n_b2', '南西'),
  g('大阪・堂島 とろ家', 'sanban_n_b2', '南西'),
  g('宮武讃岐うどん', 'sanban_n_b2', '南西'),
  // ==== 阪急三番街 南館B1F（公式マップ区画順） ====
  g('メンディングサービス', 'sanban_s_b1', '南西'),
  g('りそな銀行 セブンデイズプラザ', 'sanban_s_b1', '南西'),
  g('ミッシュマッシュ', 'sanban_s_b1', '南西'),
  g('ハートダンス', 'sanban_s_b1', '南西'),
  g('コスメキッチン', 'sanban_s_b1', '南'),
  g('ミツミネ', 'sanban_s_b1', '南'),
  g('銀座ワシントン', 'sanban_s_b1', '南東'),
  g('ノーリーズソフィー', 'sanban_s_b1', '西'),
  g('コラージュ ガリャルダガランテ', 'sanban_s_b1', '西'),
  g('ロペピクニック 三番街店', 'sanban_s_b1', '西'),
  g('パーフェクトスーツファクトリー', 'sanban_s_b1', '西'),
  g('ディノス F.O.バイ サクラフォークス', 'sanban_s_b1', '西'),
  g('ショップチャンネル大阪', 'sanban_s_b1', '北西'),
  g('カロー', 'sanban_s_b1', '北西'),
  g('ほけんの窓口', 'sanban_s_b1', '北西'),
  g('ロッサ', 'sanban_s_b1', '北西'),
  g('ハーブス 三番街店', 'sanban_s_b1', '中央'),
  g('ユナイテッドアローズ グリーンレーベルリラクシング', 'sanban_s_b1', '中央'),
  g('ピロースタンド', 'sanban_s_b1', '中央'),
  g('スロヴネンヤ ドゥセー', 'sanban_s_b1', '北'),
  g('コキュリコット', 'sanban_s_b1', '北'),
  g('フットデザイン・無重力マッサージ', 'sanban_s_b1', '北'),
  g('ストロベリーフィールズ', 'sanban_s_b1', '東'),
  g('ちいかわらんど', 'sanban_s_b1', '中央'),
  g('ナポカ', 'sanban_s_b1', '中央'),
  g('リーフ', 'sanban_s_b1', '中央'),
  g('ジンズ', 'sanban_s_b1', '北'),
  g('ヘルス＆ビューティー メトラボ', 'sanban_s_b1', '北'),
  g('ポートランド', 'sanban_s_b1', '西'),
  g('モノミュージアム', 'sanban_s_b1', '西'),
  g('フォンテーヌ クチュール', 'sanban_s_b1', '北西'),
  g('ピッコーネ・ローマ', 'sanban_s_b1', '北西'),
  g('チュニック', 'sanban_s_b1', '北西'),
  g('ラフィネ', 'sanban_s_b1', '北西'),
  g('タビインターナショナル', 'sanban_s_b1', '北'),
  g('エメ', 'sanban_s_b1', '東'),
  g('ピーツー ドッグ&キャット', 'sanban_s_b1', '東'),
  g('ビューズ アイブロウ スタジオ', 'sanban_s_b1', '東'),
  g('ファブリック トウキョウ', 'sanban_s_b1', '北東'),
  g('ドライヘッドスパ専門サロン リセット', 'sanban_s_b1', '北東'),
  g('ルージュ・ヴィフ ラクレ', 'sanban_s_b1', '南東'),
  g('プロポーションボディドレッシング', 'sanban_s_b1', '南東'),
  g('ナチュラルビューティーベーシック', 'sanban_s_b1', '東'),
  g('インティミッシミ', 'sanban_s_b1', '東'),
  g('サマンサモスモス', 'sanban_s_b1', '東'),
  g('ハニーズ', 'sanban_s_b1', '東'),
  g('フォルムアイ', 'sanban_s_b1', '北東'),
  g('上島珈琲店', 'sanban_s_b1', '北'),
  g('まねきや', 'sanban_s_b1', '北東'),
  g('鈴乃屋', 'sanban_s_b1', '北東'),
  g('きものやまと', 'sanban_s_b1', '北東'),
  // ==== 阪急三番街 南館B2F（川の流れる街・公式マップ区画順） ====
  g('こなな', 'sanban_s_b2', '南西'),
  g('うを佐', 'sanban_s_b2', '南西'),
  g('家族亭', 'sanban_s_b2', '南'),
  g('生尾', 'sanban_s_b2', '南'),
  g('とんかつKYK', 'sanban_s_b2', '南東'),
  g('ムシベジプラス', 'sanban_s_b2', '南東'),
  g('はまぐり庵 吉祥別邸', 'sanban_s_b2', '南西'),
  g('串かつ料理 活 三番街店', 'sanban_s_b2', '南西'),
  g('海鮮居酒屋あいち 三番街店', 'sanban_s_b2', '南西'),
  g('梅八', 'sanban_s_b2', '西'),
  g('うどん 兎麦', 'sanban_s_b2', '西'),
  g('大同門', 'sanban_s_b2', '西'),
  g('スキヤキフジオ', 'sanban_s_b2', '南西'),
  g('ぼてぢゅう', 'sanban_s_b2', '西'),
  g('インデアンカレー 阪急三番街店', 'sanban_s_b2', '西'),
  g('肉重 ロマン亭', 'sanban_s_b2', '西'),
  g('梅田食堂', 'sanban_s_b2', '西'),
  g('ごはん処 司', 'sanban_s_b2', '西'),
  g('帝塚山 季 TOKI', 'sanban_s_b2', '西'),
  g('グリル ロン', 'sanban_s_b2', '北西'),
  g('祭太鼓', 'sanban_s_b2', '北西'),
  g('マルモキッチン', 'sanban_s_b2', '北西'),
  g('心斎橋ミツヤ 三番街店', 'sanban_s_b2', '北西'),
  g('風流 田毎そば', 'sanban_s_b2', '北西'),
  g('つけめんTETSU', 'sanban_s_b2', '北西'),
  g('上高地 あずさ珈琲', 'sanban_s_b2', '北西'),
  g('ディッパーダン', 'sanban_s_b2', '北'),
  g('リバーカフェ', 'sanban_s_b2', '北'),
  g('スシ海鮮酒場 おか長', 'sanban_s_b2', '北西'),
  g('しゃぶ菜', 'sanban_s_b2', '北'),
  g('御鷹茶屋', 'sanban_s_b2', '北東'),
  g('シルクレーム', 'sanban_s_b2', '南東'),
  g('クワトロナポリ', 'sanban_s_b2', '東'),
  g('パスタ・デ・パスタ', 'sanban_s_b2', '南東'),
  g('とろさば料理専門店 SABAR', 'sanban_s_b2', '東'),
  g('ぶぶ亭', 'sanban_s_b2', '東'),
  g('牛たんとお酒 もりの屋', 'sanban_s_b2', '東'),
  g('ラーメン横綱', 'sanban_s_b2', '北東'),
  g('台湾甜商店', 'sanban_s_b2', '北東'),
  g('昔洋食みつけ亭', 'sanban_s_b2', '北東'),
  g('しのぶ庵', 'sanban_s_b2', '北東'),
  g('雲仙', 'sanban_s_b2', '北東'),
  g('梅蘭', 'sanban_s_b2', '南東'),
  g('梅香 メイシャン', 'sanban_s_b2', '東'),
  g('正起屋 三番街店', 'sanban_s_b2', '東'),
  g('がんこ寿司', 'sanban_s_b2', '東'),
  g('カレーハウス サンマルコ', 'sanban_s_b2', '北東'),
  g('島ぬ風', 'sanban_s_b2', '北東'),
  g('菓匠館 福壽堂秀信', 'sanban_s_b2', '南西'),
  g('はちみつ茶葉園', 'sanban_s_b2', '南西'),
  g('ステラおばさんのクッキー', 'sanban_s_b2', '西'),
  g('神戸・元町 花見屋', 'sanban_s_b2', '西'),
  g('トップス', 'sanban_s_b2', '南'),
  g('茶の彩', 'sanban_s_b2', '中央'),
  g('キッチンキッチン', 'sanban_s_b2', '西'),
  g('モロゾフ', 'sanban_s_b2', '中央'),
  g('喫茶トリコロール', 'sanban_s_b2', '中央'),
  g('宇治園 喫茶去', 'sanban_s_b2', '中央'),
  g('クックハウス 三番街店', 'sanban_s_b2', '東'),
  g('金澤スッポン堂', 'sanban_s_b2', '北'),
  g('マネケン', 'sanban_s_b2', '東'),
  g('茶青花', 'sanban_s_b2', '中央'),
  g('ムーミンカフェスタンド', 'sanban_s_b2', '東'),
  g('ゴディバ 阪急三番街店', 'sanban_s_b2', '東'),
  g('キムラ フルーツパーラー', 'sanban_s_b2', '北'),
  g('アンティコカフェ アルアビス 三番街店', 'sanban_s_b2', '南東'),
  g('サロン ド ロワイヤル', 'sanban_s_b2', '南'),
  g('カフェ バーンホーフ', 'sanban_s_b2', '南'),
  g('デリカKYK', 'sanban_s_b2', '南'),
  g('銀座コージーコーナー', 'sanban_s_b2', '中央'),
  g('手づくり惣菜 咲菜', 'sanban_s_b2', '南'),
  g('大起水産 街のみなと', 'sanban_s_b2', '南'),
  g('成城石井 阪急三番街店', 'sanban_s_b2', '中央'),
  g('べジフルマーケット', 'sanban_s_b2', '南'),
  g('ちひろ菓子店', 'sanban_s_b2', '中央'),
  g('台北餃子張記 三番街店', 'sanban_s_b2', '東'),
  // ==== ホワイティうめだ ノースモール1（北=サニーテラス→南=ポケットパーク方面） ====
  s('ミスタークイックマン 北店', 'whity_north1', 1, '西'),
  s('サーティワンアイスクリーム', 'whity_north1', 2, '西'),
  s('ビアードパパ', 'whity_north1', 3, '西'),
  s('and大阪店', 'whity_north1', 4, '東'),
  s('理容清水', 'whity_north1', 5, '西'),
  s('やきにく萬野', 'whity_north1', 6, '東'),
  s('むさし乃', 'whity_north1', 7, '西'),
  s('海鮮居酒屋あいち', 'whity_north1', 8, '東'),
  s('クックデリ御膳', 'whity_north1', 9, '西'),
  s('赤垣屋', 'whity_north1', 10, '西'),
  s('梅田酒場 すし金', 'whity_north1', 11, '東'),
  s('立呑み処 七津屋', 'whity_north1', 12, '西'),
  s('しゃぶしゃぶぐるまん', 'whity_north1', 13, '東'),
  s('大ざわ', 'whity_north1', 14, '東'),
  s('お好み焼 ゆかり', 'whity_north1', 15, '西'),
  s('中央軒', 'whity_north1', 16, '東'),
  s('地産酒場 十八番', 'whity_north1', 17, '西'),
  s('大阪木津市場 天はな', 'whity_north1', 18, '東'),
  s('きしめんあまの', 'whity_north1', 19, '西'),
  s('正起屋', 'whity_north1', 20, '東'),
  s('ミスタードーナツ ホワイティうめだショップ', 'whity_north1', 21, '西'),
  s('ヨネヤ', 'whity_north1', 22, '西'),
  s('ドトールコーヒーショップ', 'whity_north1', 23, '東'),
  s('串かつ料理 活', 'whity_north1', 24, '西'),
  s('玉乃光酒場 かつお天国', 'whity_north1', 25, '東'),
  s('風流 田舎そば', 'whity_north1', 26, '西'),
  s('直福', 'whity_north1', 27, '東'),
  s('福すし', 'whity_north1', 28, '東'),
  s('タレかつ飯 TSUI TSUI', 'whity_north1', 29, '西'),
  s('じゅろく別邸', 'whity_north1', 30, '東'),
  s('Quark（ロレックス専門店）', 'whity_north1', 31, '西'),
  s('立ち萬', 'whity_north1', 32, '西'),
  s('タリーズコーヒー &TEA', 'whity_north1', 33, '東'),
  s('鳥の巣', 'whity_north1', 34, '西'),
  s('CAFE 英國屋', 'whity_north1', 35, '西'),
  s('夢ステーション うめだ北店', 'whity_north1', 36, '東'),
  s('KIEFEL', 'whity_north1', 37, '西'),
  s('チケット7プレイガイド', 'whity_north1', 38, '西'),
  s('三菱UFJ銀行ATM', 'whity_north1', 39, '西'),
  s('VIE DE FRANCE', 'whity_north1', 40, '東'),
  // ==== ホワイティうめだ ノースモール2（南西→北東=阪急東通り入口） ====
  s('Bechamel Cafe', 'whity_north2', 1, '南東'),
  s('丼丼亭', 'whity_north2', 2, '南東'),
  s('赤白 ホワイティうめだ店', 'whity_north2', 3, '南東'),
  s('堂山食堂', 'whity_north2', 4, '北西'),
  s('串かつだるま', 'whity_north2', 5, '南東'),
  s('すし酒場 さしす', 'whity_north2', 6, '北西'),
  s('油そば きりん寺', 'whity_north2', 7, '南東'),
  s('ウオチカ。', 'whity_north2', 8, '北西'),
  s('牛たん焼き仙台辺見', 'whity_north2', 9, '南東'),
  s('Refresh hands', 'whity_north2', 10, '北西'),
  s('屋台餃子 あらき', 'whity_north2', 11, '南東'),
  // ==== ホワイティうめだ センターモール（西=梅田駅方面→東=ポケットパーク） ====
  s('リンツ ショコラ ブティック', 'whity_center', 1, '北'),
  s('We♡donut×TAKAGI COFFEE', 'whity_center', 2, '南'),
  s('ミスタークイックマン', 'whity_center', 3, '北西'),
  s('conoka（花）', 'whity_center', 4, '北西'),
  s('piccoLo（カレー）', 'whity_center', 5, '北'),
  s('CAFE BREAK', 'whity_center', 6, '南'),
  s('R&K リサイクルキング', 'whity_center', 7, '北'),
  s('セブン銀行ATM センターモール', 'whity_center', 8, '北'),
  s('Afternoon Tea LIVING', 'whity_center', 9, '北'),
  s('心斎橋ミツヤ', 'whity_center', 10, '北'),
  s('Afternoon Tea TEAROOM', 'whity_center', 11, '北'),
  s('ティラミス専門店 リバーレ', 'whity_center', 12, '北'),
  // ==== ホワイティうめだ サウスモール（北西=案内所前→南東=第4ビル/ディアモール方面） ====
  s('夢ステーション うめだ中央店', 'whity_south', 1, '東'),
  s('Miru+（コンタクト）', 'whity_south', 2, '東'),
  s('阪神ドラッグ 梅田地下店', 'whity_south', 3, '東'),
  s('旭屋書店 梅田地下街店', 'whity_south', 4, '東'),
  s('丹青堂', 'whity_south', 5, '西'),
  s('SANRINO（シューズ）', 'whity_south', 6, '東'),
  s('文字の店', 'whity_south', 7, '西'),
  s('花直園芸', 'whity_south', 8, '東'),
  s('買取大吉', 'whity_south', 9, '東'),
  s('セブン銀行ATM サウスモール', 'whity_south', 10, '西'),
  // ==== ホワイティうめだ mikke（西→東・列はunknownの店は交互配置） ====
  s('HIRAMEKI.', 'whity_mikke', 1, '南'),
  s("S'appuyer", 'whity_mikke', 2, '南'),
  s('SENSE OF PLACE by URBAN RESEARCH', 'whity_mikke', 3),
  s('GLACIER lusso', 'whity_mikke', 4, '南'),
  s('Histoire', 'whity_mikke', 5, '北'),
  s('ANIMI MOTIO', 'whity_mikke', 6),
  s('ear PAPILLONNER', 'whity_mikke', 7, '北'),
  s('le VERT', 'whity_mikke', 8, '南'),
  s('&.NOSTALGIA', 'whity_mikke', 9),
  s('tocco closet', 'whity_mikke', 10, '南'),
  s('Lois CRAYON relax', 'whity_mikke', 11),
  s('fitfit', 'whity_mikke', 12, '北'),
  s('inner shop Chelsea', 'whity_mikke', 13, '北'),
  s('tutuanna', 'whity_mikke', 14, '南'),
  s('Shop 無（帽子）', 'whity_mikke', 15),
  s('BE BIRTH 美スギ', 'whity_mikke', 16),
  s('Anker Store', 'whity_mikke', 17, '北'),
  s('Bleu Bleuet', 'whity_mikke', 18),
  // ==== ホワイティうめだ FARURU（南西→北東） ====
  s('Bag select shop fav', 'whity_faruru', 1, '南'),
  s('Zoff ホワイティうめだ店', 'whity_faruru', 2),
  s('fleuve', 'whity_faruru', 3),
  s('DoCLASSE', 'whity_faruru', 4, '南'),
  s('DHC', 'whity_faruru', 5, '西'),
  s('LUSH', 'whity_faruru', 6, '北'),
  s('Via Lattea platino', 'whity_faruru', 7, '南東'),
  s('Via Lattea aurino', 'whity_faruru', 8, '南東'),
  s('眼鏡市場', 'whity_faruru', 9, '北西'),
  s('七宝 SHIPPO', 'whity_faruru', 10, '南東'),
  s('帽子屋Flava', 'whity_faruru', 11, '南東'),
  s('CRAVATTERIA TAM', 'whity_faruru', 12, '南東'),
  s('白牡丹', 'whity_faruru', 13, '南東'),
  s('コクミン FARURU店', 'whity_faruru', 14, '北西'),
  s('REGAL SHOES', 'whity_faruru', 15, '南東'),
  s('Marusho', 'whity_faruru', 16, '南東'),
  // ==== ホワイティうめだ プチシャン（北=Nu茶屋町→南=三番街連絡口） ====
  s('エフワン', 'whity_petit', 1, '東'),
  s('保険クリニック', 'whity_petit', 2, '西'),
  s('MAUA', 'whity_petit', 3, '東'),
  s('あい鍼灸院・接骨院 プチシャン', 'whity_petit', 4, '西'),
  s('和み庵', 'whity_petit', 5, '東'),
  s('B-THREE', 'whity_petit', 6, '西'),
  s('おしゃれ工房＋スマホクリニック', 'whity_petit', 7, '東'),
  s('中古楽器専門店Qsic', 'whity_petit', 8, '西'),
  s('NATURAL KITCHEN', 'whity_petit', 9, '東'),
  s('au Style', 'whity_petit', 10, '西'),
  s('占いの館キセキ', 'whity_petit', 11, '東'),
  s('渡部眼科クリニック', 'whity_petit', 12, '西'),
  s('アイシティ', 'whity_petit', 13, '東'),
  s('Tools（画材・文具）', 'whity_petit', 14, '西'),
  s('美スギ プチシャン店', 'whity_petit', 15, '東'),
  s('BRICK HOUSE シャツ工房', 'whity_petit', 16, '西'),
  s('コクミン プチシャン店', 'whity_petit', 17, '西'),
  s('nooto', 'whity_petit', 18, '東'),
  s('セブン銀行ATM プチシャン', 'whity_petit', 19, '西'),
  // ==== ホワイティうめだ ポケットパーク（広場西〜北西縁） ====
  s('夢ぎゃらりぃハトキン', 'whity_pocket', 1, '西'),
  s('casaneilo', 'whity_pocket', 2, '北'),
  s('クックハウス', 'whity_pocket', 3, '北'),
  // ==== ホワイティうめだ イーストモール（西=ポケットパーク→東=泉の広場） ====
  s('成城石井 ホワイティうめだ店', 'whity_east', 1, '北'),
  s('まるしげ', 'whity_east', 2, '南'),
  s('たこ八', 'whity_east', 3, '北'),
  s('りそな銀行ATM', 'whity_east', 4, '南'),
  s('3COINS', 'whity_east', 5, '北'),
  s('卵と私', 'whity_east', 6, '南'),
  s('リフレッシュハンズ 泉の広場店', 'whity_east', 7, '南'),
  s('コクミン イーストモール店', 'whity_east', 8, '北'),
  s('LUNA EARTH', 'whity_east', 9, '南'),
  s('belle-ville', 'whity_east', 10, '南'),
  s('CAFE 英國屋 NORTH', 'whity_east', 11, '北'),
  s('蕎麦居酒屋 弦', 'whity_east', 12, '南'),
  s('古潭（らーめん）', 'whity_east', 13, '北'),
  s('膳や', 'whity_east', 14, '南'),
  s('うどん王', 'whity_east', 15, '南'),
  s('WithGreen ホワイティうめだ店', 'whity_east', 16, '北'),
  s('大阪トンテキ', 'whity_east', 17, '南'),
  s('大起水産 回転寿司', 'whity_east', 18, '北'),
  s('洋麺屋 五右衛門', 'whity_east', 19, '南'),
  s('大阪炒飯倶楽部', 'whity_east', 20, '南'),
  s('騒豆花', 'whity_east', 21, '北'),
  s('セブン銀行ATM イーストモール', 'whity_east', 22, '南'),
  s('ごちとん（豚汁定食）', 'whity_east', 23, '北'),
  s('新潟をこめ', 'whity_east', 24, '南'),
  s('モスバーガー ホワイティうめだ店', 'whity_east', 25, '北'),
  s('甘党まえだ', 'whity_east', 26, '北'),
  s('スターバックスコーヒー ホワイティうめだ店', 'whity_east', 27, '南'),
  s('ブルーレモン #CHIKAMISE', 'whity_east', 28, '西'),
  s('炙り肉寿司 コマツバラファーム', 'whity_east', 29, '北'),
  // ==== ホワイティうめだ NOMOKA（南=泉の広場→北=中崎町方面） ====
  s('もんじゃのえびせん', 'whity_nomoka', 1, '東'),
  s('CRAFT BEER MARKET', 'whity_nomoka', 2, '西'),
  s('台北餃子張記', 'whity_nomoka', 3, '西'),
  s('イタリアン魚酒場アルバータ', 'whity_nomoka', 4, '東'),
  s('京の串揚げ 祇園囃子', 'whity_nomoka', 5, '東'),
  s('川北商店（焼鳥）', 'whity_nomoka', 6, '西'),
  s('YEBISU BAR', 'whity_nomoka', 7, '東'),
  s('博多 天神ホルモン', 'whity_nomoka', 8, '西'),
  s('ミアスタンド', 'whity_nomoka', 9, '東'),
  s('わすれな草', 'whity_nomoka', 10, '東'),
  s('浪花ハイボール', 'whity_nomoka', 11, '東'),
  s('沖縄酒場あしびなー', 'whity_nomoka', 12, '西'),
  s('鮨酒場てっぺい', 'whity_nomoka', 13, '東'),
  s('韓国酒場コッキオ', 'whity_nomoka', 14, '西'),
  s('天ぷら大吉', 'whity_nomoka', 15, '東'),
  s('漁師酒場 あらき', 'whity_nomoka', 16, '西'),
  s('徳田酒店', 'whity_nomoka', 17, '西'),
  // ==== ディアモール大阪 ファッショナブルストリート（西→東・公式マップ準拠） ====
  s('フレームワーク', 'diamor_fashion', 1),
  s('LAKOLE', 'diamor_fashion', 2),
  s('ビス', 'diamor_fashion', 3),
  s('ブーレ', 'diamor_fashion', 4, '北'),
  s('デシグアル', 'diamor_fashion', 5, '南'),
  s('WithGreen ディアモール店', 'diamor_fashion', 6, '北'),
  s('卑弥呼', 'diamor_fashion', 7, '南'),
  s('ムジ コム（無印良品）', 'diamor_fashion', 8, '北'),
  s('ITAL STYLE', 'diamor_fashion', 9, '南'),
  s('ロペピクニック ディアモール店', 'diamor_fashion', 10, '北'),
  s('パラスパレス', 'diamor_fashion', 11, '南'),
  s('GINZA Global Style', 'diamor_fashion', 12, '北'),
  s('大阪市梅田サービスカウンター', 'diamor_fashion', 13, '北'),
  s('DoCLASSE メンズ店', 'diamor_fashion', 14, '南'),
  s('アンティコカフェ アルアビス', 'diamor_fashion', 15, '南'),
  s('ケユカ', 'diamor_fashion', 16, '北'),
  s('ハーブス ディアモール店', 'diamor_fashion', 17, '南'),
  s('ダイアナ', 'diamor_fashion', 18, '北'),
  s('TEA18', 'diamor_fashion', 19, '南'),
  s('SUBWAY', 'diamor_fashion', 20, '南'),
  s('ムシベジプラスカフェ', 'diamor_fashion', 21, '北'),
  s('サンマルクカフェ', 'diamor_fashion', 22, '北'),
  s('TO THE HERBS', 'diamor_fashion', 23, '南'),
  s('ワタナベ眼科', 'diamor_fashion', 24, '北'),
  s('ファミリーマート ファッショナブルストリート店', 'diamor_fashion', 25, '北'),
  s('ZETTERIA', 'diamor_fashion', 26, '南'),
  s('そじ坊', 'diamor_fashion', 27, '北'),
  // ==== ディアモール大阪 マーケットストリート（円形広場→北東・公式マップ準拠） ====
  s('ピエール・エルメ・パリ', 'diamor_market', 1, '北西'),
  s('ヴェンキ', 'diamor_market', 2, '南東'),
  s('クリスピー・クリーム・ドーナツ', 'diamor_market', 3, '南東'),
  s('タリーズコーヒー ディアモール大阪', 'diamor_market', 4, '北西'),
  s('ゆうちょ銀行ATM', 'diamor_market', 5, '南東'),
  s('アモスタイル バイ トリンプ', 'diamor_market', 6, '北西'),
  s('COFFEE STYLE UCC', 'diamor_market', 7, '南東'),
  s('サルート by ワコール', 'diamor_market', 8, '北西'),
  s('atelier haruka', 'diamor_market', 9, '南東'),
  s('フットデザイン ディアモール店', 'diamor_market', 10, '北西'),
  s('美スギ・コスメガーデンS', 'diamor_market', 11, '南東'),
  s('aiicosme', 'diamor_market', 12, '南東'),
  s('美スギ・コスメガーデン', 'diamor_market', 13, '北西'),
  s('久世福商店 ディアモール店', 'diamor_market', 14, '南東'),
  s('美スギ・SK-II', 'diamor_market', 15, '北西'),
  s('クイーンズウェイ ディアモール店', 'diamor_market', 16, '南東'),
  s('UQスポット', 'diamor_market', 17, '北西'),
  s('ドトールコーヒーショップ ディアモール店', 'diamor_market', 18, '南東'),
  s('サーティワンアイスクリーム ディアモール店', 'diamor_market', 19, '北西'),
  s('ジンズ ディアモール店', 'diamor_market', 20, '北西'),
  s('ファミリーマート マーケットストリート店', 'diamor_market', 21, '南東'),
  s('保険クリニック ディアモール店', 'diamor_market', 22, '北西'),
  s('青山フラワーマーケット', 'diamor_market', 23, '南東'),
  // ==== ディアモール大阪 カジュアルストリート（北=阪神側→円形広場→南=堂島方面） ====
  s('三井住友銀行ATM', 'diamor_casual', 1, '東'),
  s('ルクールブラン', 'diamor_casual', 2, '西'),
  s('チャールズ & キース', 'diamor_casual', 3, '東'),
  s('楽天モバイル ディアモール大阪', 'diamor_casual', 4, '西'),
  s('セブン銀行ATM ディアモール', 'diamor_casual', 5, '西'),
  s('GODIVA café DIAMOR OSAKA', 'diamor_casual', 6, '西'),
  s('CocoLe by le-noble', 'diamor_casual', 7, '東'),
  s('DIAMOR and.', 'diamor_casual', 8, '西'),
  s('12 Twelve Agenda', 'diamor_casual', 9, '西'),
  s('アーバンリサーチ ロッソ', 'diamor_casual', 10, '西'),
  s('ストラ', 'diamor_casual', 11, '西'),
  s('YECCA VECCA', 'diamor_casual', 12, '西'),
  s('Jil Purple', 'diamor_casual', 13, '西'),
  s('テチチ', 'diamor_casual', 14, '西'),
  s('ミスターミニット', 'diamor_casual', 15, '東'),
  s('KASHIYAMA', 'diamor_casual', 16, '西'),
  s('リフレッシュハンズ ディアモール店', 'diamor_casual', 17, '西'),
  s('りそな・関西みらい銀行ATM', 'diamor_casual', 18, '東'),
  // ==== ディアモール大阪 バラエティストリート（円形広場→南東・公式マップ準拠） ====
  s('コクミン ディアモール店', 'diamor_variety', 1, '北東'),
  s('ショップイン', 'diamor_variety', 2, '北東'),
  s('チュチュアンナ ディアモール店', 'diamor_variety', 3, '北東'),
  s('グレディブリリアン ディアモール店', 'diamor_variety', 4, '北東'),
  s('ACE BAGS&LUGGAGE', 'diamor_variety', 5, '北東'),
  s('Histoire ディアモール店', 'diamor_variety', 6, '南西'),
  s('オリヒカ', 'diamor_variety', 7, '北東'),
  s('ランダ', 'diamor_variety', 8, '南西'),
  s('ATELIER ALBION', 'diamor_variety', 9, '北東'),
  s('LIB（レザーグッズ）', 'diamor_variety', 10, '南西'),
  s('サマンサモスモス ディアモール店', 'diamor_variety', 11, '北東'),
  s('ゾフ ディアモール店', 'diamor_variety', 12, '南西'),
  s('クリア', 'diamor_variety', 13, '北東'),
  s('ハートダンス ディアモール店', 'diamor_variety', 14, '北東'),
  s('ダブリューダブリューエス', 'diamor_variety', 15, '南西'),
  s('コキュリコット ディアモール店', 'diamor_variety', 16, '北東'),
  s('ディアモールチャンスセンター（宝くじ）', 'diamor_variety', 17, '北東'),
  s('ドコモショップ', 'diamor_variety', 18, '西'),
  // ==== ドーチカ（公式マップ区画番号を突合・北端→南端の通し順・全53店 2026-07） ====
  s('三菱UFJ銀行ATM', 'dotica', 1, '西'),
  s('新梅田コクミン薬局', 'dotica', 2, '東'),
  s('KIEFEL COFFEE', 'dotica', 3, '西'),
  s('ファミリーマート ドーチカ店', 'dotica', 4, '東'),
  s('plus on ドーチカ店', 'dotica', 5, '西'),
  s('レオニダス 大阪梅田店', 'dotica', 6, '西'),
  s('インデアンカレー 堂島店', 'dotica', 7, '東'),
  s('東京油組総本店 ドーチカ組', 'dotica', 8, '西'),
  s('newKOBE 堂島店', 'dotica', 9, '東'),
  s('わたしのダイニング × SAKAGURA', 'dotica', 10, '西'),
  s('みずほ銀行ATM', 'dotica', 11, '東'),
  s('ダル食堂 堂島地下街店', 'dotica', 12, '西'),
  s('ミスタークイックマン', 'dotica', 13, '東'),
  s('りそな銀行ATM', 'dotica', 14, '東'),
  s('コクミンドラッグ ドーチカ店', 'dotica', 15, '西'),
  s('ほけん百花 梅田ドーチカ店', 'dotica', 16, '東'),
  s('J・マーケット大阪ドーチカ店', 'dotica', 17, '東'),
  s('文字の店 堂島', 'dotica', 18, '西'),
  s('じゃんぱら大阪堂島店', 'dotica', 19, '東'),
  s('BIG VISION', 'dotica', 20, '西'),
  s('中央コンタクト', 'dotica', 21, '西'),
  s('コクミンドラッグ 堂島店', 'dotica', 22, '東'),
  s('ちぐさ大阪うめだ支店', 'dotica', 23, '西'),
  s('リフレッシュ工房オズ 堂島店', 'dotica', 24, '西'),
  s('セブン銀行ATM', 'dotica', 25, '東'),
  s('時計修理工房 白金堂 大阪梅田ドーチカ店', 'dotica', 26, '西'),
  s('西梅田眼科クリニック', 'dotica', 27, '東'),
  s('青森・岩手えぇもんショップ', 'dotica', 28, '西'),
  s('TRARIUM by ACE', 'dotica', 29, '東'),
  s('Buena.', 'dotica', 30, '西'),
  s('KENFORD堂島地下街店', 'dotica', 31, '東'),
  s('梅田もりわき骨盤鍼灸整骨院', 'dotica', 32, '西'),
  s('千鳥屋宗家 堂島店', 'dotica', 33, '東'),
  s('Perfect Suit FActory', 'dotica', 34, '西'),
  s('ダイソー', 'dotica', 35, '西'),
  s('クックデリ御膳 ドーチカ店', 'dotica', 36, '東'),
  s('三井住友銀行ATM', 'dotica', 37, '西'),
  s('ドトールコーヒーショップドーチカ', 'dotica', 38, '東'),
  s('おたからや梅田ドーチカ店', 'dotica', 39, '西'),
  s('KUSELESS', 'dotica', 40, '西'),
  s('吉野家', 'dotica', 41, '西'),
  s('都由堂島店', 'dotica', 42, '東'),
  s('かっぽうぎ ドーチカ店', 'dotica', 43, '西'),
  s('Barber the GM 堂島', 'dotica', 44, '東'),
  s('おきがる串家物語', 'dotica', 45, '西'),
  s('お酒の美術館 ドーチカ店', 'dotica', 46, '東'),
  s('おらが蕎麦', 'dotica', 47, '西'),
  s('ドットミーティング堂島貸会議室', 'dotica', 48, '東'),
  s('海鮮居酒屋あいち', 'dotica', 49, '西'),
  s('中央軒 ドーチカ店', 'dotica', 50, '東'),
  s('つけ麺専門店 三田製麺所 ドーチカ店', 'dotica', 51, '西'),
  s('CAFÉ ONthe', 'dotica', 52, '西'),
  s('自家製麺杵屋', 'dotica', 53, '東'),
  // ==== ルクアB2 バルチカ（公式マップ2026-06版・N=上確認済み・全26店） ====
  g('焼肉トラジ', 'barchika', '北西'),
  g('創業明治23年 徳田酒店', 'barchika', '北西'),
  g('韓国酒場 コッキオ', 'barchika', '北西'),
  g('炭火焼鳥 権兵衛', 'barchika', '北西'),
  g('あべの たこやき やまちゃん', 'barchika', '西'),
  g('となりのジャックとマチルダ', 'barchika', '西'),
  g('やきにく 萬野', 'barchika', '西'),
  g('松葉', 'barchika', '中央'),
  g('オステリア・ガウダンテ', 'barchika', '中央'),
  g('梅田麹室 豊祝', 'barchika', '中央'),
  g('旧ヤム鐵道', 'barchika', '東'),
  g('鮨ト酒 日々晴々', 'barchika', '東'),
  g('ハモネリア ベジョータ ギョクロ', 'barchika', '東'),
  g('フレンチおでん「赤白」コウハク', 'barchika', '東'),
  g('うなぎ 串焼き いづも', 'barchika', '南西'),
  g('魚屋スタンドふじ子', 'barchika', '南西'),
  g('チャイニーズ ビストロ 蘭亭', 'barchika', '南西'),
  g('クラフトビアマーケット', 'barchika', '南西'),
  g('銀座 篝', 'barchika', '南'),
  g('タイ国政府認定三ツ星レストラン クンテープ', 'barchika', '南'),
  g('本町製麺所 天', 'barchika', '南'),
  g('お好み たまちゃん', 'barchika', '南'),
  g('もつ焼ウッチャン', 'barchika', '南'),
  g('羽根つき焼小籠包 鼎\'s（Din\'s）', 'barchika', '南東'),
  g('人類みな麺類Premium', 'barchika', '南東'),
  g('宮崎酒場 ゑびす', 'barchika', '南東'),
  // ==== ルクアB2 ルクアフードホール（同上・全15店） ====
  g('キッチン＆マーケット', 'foodhall', '北西'),
  g('スターバックス（リザーブバー）', 'foodhall', '北東'),
  g('北摂スパイス研究所', 'foodhall', '中央'),
  g('串やき まんてん', 'foodhall', '中央'),
  g('サーティワンアイスクリーム', 'foodhall', '東'),
  g('ミャムミャム', 'foodhall', '東'),
  g('クリスピー・クリーム・ドーナツ', 'foodhall', '東'),
  g('ゴンチャ', 'foodhall', '東'),
  g('築地食堂 源ちゃん', 'foodhall', '南'),
  g('とんかつ 新宿さぼてん', 'foodhall', '南'),
  g('マルトメ・ザ・ジューサリー パフェテリア', 'foodhall', '南東'),
  g('北極星', 'foodhall', '南東'),
  g('クア・アイナ', 'foodhall', '南東'),
  g('だし茶漬け+肉うどん えん', 'foodhall', '南東'),
  g('ビフテキ重・肉飯 ロマン亭', 'foodhall', '南東'),
  // ==== ekimo梅田（中南改札→南改札の並び順・全12店） ====
  s('J・マーケット', 'ekimo', 1, '東'),
  s('オーエスドラッグ', 'ekimo', 2, '東'),
  s('ノムラクリーニング', 'ekimo', 3, '西'),
  s('LUNA EARTH', 'ekimo', 4, '東'),
  s('MUJI com', 'ekimo', 5, '西'),
  s('karendo', 'ekimo', 6, '東'),
  s('UNIQLO', 'ekimo', 7, '西'),
  s('メガネスーパーコンタクト', 'ekimo', 8, '東'),
  s('JINS', 'ekimo', 9, '西'),
  s('三井住友銀行ATMコーナー', 'ekimo', 10, '西'),
  s('ミスタードーナツ', 'ekimo', 11, '東'),
  s('八天堂', 'ekimo', 12, '東'),
  // ==== ヒルトンプラザ ウエストB1F（公式マップ・回転補正済みセル・全7店 2026-07） ====
  g('トゥミ', 'hilton_west_b1', '東'),
  g('ゲンテン', 'hilton_west_b1', '東'),
  g('プロテカ', 'hilton_west_b1', '中央'),
  g('ゼロハリバートン', 'hilton_west_b1', '南'),
  g('アッシュ・アール・エム', 'hilton_west_b1', '中央'),
  g('アーティザンPJ', 'hilton_west_b1', '中央'),
  g('ハンティングワールド', 'hilton_west_b1', '北'),
  // ==== ヒルトンプラザ ウエストB2F（公式マップ・回転補正済みセル・全6店 2026-07） ====
  g('焼肉トラジ ヒルトンプラザ店', 'hilton_west_b2', '北東'),
  g('ヤサイフレンチ NR', 'hilton_west_b2', '東'),
  g('廣東料理 民生', 'hilton_west_b2', '東'),
  g('虎連坊', 'hilton_west_b2', '南'),
  g('うなぎ四代目菊川', 'hilton_west_b2', '中央'),
  g('寿司 なかご', 'hilton_west_b2', '北'),
  // ==== ヒルトンプラザ イーストB1F（公式マップ・回転補正済みセル・全14店 2026-07） ====
  g('エルメス', 'hilton_east_b1', '北'),
  g('ペセリコ', 'hilton_east_b1', '中央'),
  g('エルマンノ シェルヴィーノ', 'hilton_east_b1', '西'),
  g('アドルフォ ドミンゲス', 'hilton_east_b1', '西'),
  g('ラザール ダイヤモンド ブティック', 'hilton_east_b1', '西'),
  g('グラスファクトリー', 'hilton_east_b1', '西'),
  g('ロッサ ヒルトンプラザ店', 'hilton_east_b1', '南西'),
  g('ケーニヒスクローネ カフェテリア', 'hilton_east_b1', '中央'),
  g('スヴェンソン 梅田サロン', 'hilton_east_b1', '東'),
  g('ピュア坪内', 'hilton_east_b1', '南東'),
  g('ヘアサロン大野', 'hilton_east_b1', '南東'),
  g('シーボン フェイシャリストサロン', 'hilton_east_b1', '南'),
  g('ジョイフル恵利', 'hilton_east_b1', '南'),
  g('リーン・ロゼ', 'hilton_east_b1', '南'),
  // ==== ヒルトンプラザ イーストB2F（公式マップ・回転補正済みセル・全8店 2026-07） ====
  g('天婦羅 新喜楽', 'hilton_east_b2', '北'),
  g('とり酒場 博多華善 梅田店', 'hilton_east_b2', '西'),
  g('バー・サンボア', 'hilton_east_b2', '西'),
  g('醗酵食堂 HASSHOKU', 'hilton_east_b2', '中央'),
  g('北海道 キタ酒場', 'hilton_east_b2', '中央'),
  g('楽食倶楽部 裏小路牛肉店', 'hilton_east_b2', '東'),
  g('焼肉・しゃぶしゃぶ たちばな', 'hilton_east_b2', '中央'),
  g('四季自然喰処 たちばな', 'hilton_east_b2', '南'),
  // ==== ハービスPLAZA B1F（公式マップ・回転補正済みセル・全6店 2026-07） ====
  g('Be Happy! 789 (FMスタジオ)', 'herbis_plaza_b1', '南東'),
  g('ムレスナティー 大阪', 'herbis_plaza_b1', '南'),
  g('シルベストサイクル', 'herbis_plaza_b1', '中央'),
  g('チュース ショップ', 'herbis_plaza_b1', '中央'),
  g('ミズノゴルフスタジオ', 'herbis_plaza_b1', '北西'),
  g('アルチビオ', 'herbis_plaza_b1', '西'),
  // ==== ハービスPLAZA B2F（公式マップ・回転補正済みセル・全17店 2026-07） ====
  g('美食酒場 クラウ', 'herbis_plaza_b2', '北東'),
  g('ブーランジェリー ブルディガラ', 'herbis_plaza_b2', '東'),
  g('すきやき・しゃぶしゃぶ 神戸牛 石田', 'herbis_plaza_b2', '北東'),
  g('牛たん焼き 仙台辺見', 'herbis_plaza_b2', '北東'),
  g('クレープリースタンド・シャンデレール', 'herbis_plaza_b2', '北東'),
  g('信州そば処 そじ坊', 'herbis_plaza_b2', '東'),
  g('丸福珈琲店 ハービス店', 'herbis_plaza_b2', '東'),
  g('ラブテーブル', 'herbis_plaza_b2', '北'),
  g('魚と上方うまいもん あんばい', 'herbis_plaza_b2', '中央'),
  g('焼肉こじま 離れ', 'herbis_plaza_b2', '中央'),
  g('ステーキのあさくま', 'herbis_plaza_b2', '中央'),
  g('千房 ハービス店', 'herbis_plaza_b2', '北'),
  g('コリアンダイニング 李朝園', 'herbis_plaza_b2', '北'),
  g('博多 火の音水の音', 'herbis_plaza_b2', '北'),
  g('センバキッチン グリーンハウス', 'herbis_plaza_b2', '中央'),
  g('生醤油うどんとお酒 醤屋万吉', 'herbis_plaza_b2', '中央'),
  g('西梅田 禅園', 'herbis_plaza_b2', '西'),
  // ==== ハービスPLAZA ENT B1F（公式マップ・回転補正済みセル・全6店 2026-07） ====
  g('エクスクルーシブ ギャラリー', 'herbis_ent_b1', '北'),
  g('エクスクルーシブ', 'herbis_ent_b1', '中央'),
  g('ミッドウエスト', 'herbis_ent_b1', '中央'),
  g('神戸餃子 オレギョ', 'herbis_ent_b1', '南'),
  g('三菱UFJ銀行ATM ハービス', 'herbis_ent_b1', '北西'),
  g('占いサロン イディア', 'herbis_ent_b1', '西'),
  // ==== ハービスPLAZA ENT B2F（公式マップ・回転補正済みセル・全17店 2026-07） ====
  g('デクリック', 'herbis_ent_b2', '北東'),
  g('パティスリー＆カフェ デリーモ', 'herbis_ent_b2', '北東'),
  g('パーフェクトポーション', 'herbis_ent_b2', '東'),
  g('ソブ ダブルスタンダードクロージング', 'herbis_ent_b2', '中央'),
  g('ヴァルカナイズ・ロンドン', 'herbis_ent_b2', '北'),
  g('ジョン スメドレー', 'herbis_ent_b2', '中央'),
  g('グリローズ', 'herbis_ent_b2', '北'),
  g('エポカ ザ ショップ', 'herbis_ent_b2', '中央'),
  g('アイヴァン リュクス', 'herbis_ent_b2', '中央'),
  g('ヌナ', 'herbis_ent_b2', '北'),
  g('アドレス', 'herbis_ent_b2', '北'),
  g('アンティコカフェ アルアビス ハービス店', 'herbis_ent_b2', '北'),
  g('ラルコバレーノ', 'herbis_ent_b2', '中央'),
  g('コテラック', 'herbis_ent_b2', '中央'),
  g('エクスクルーシブ プラス', 'herbis_ent_b2', '中央'),
  g('プリティ・バレリーナ', 'herbis_ent_b2', '西'),
  g('ビルボードライブ大阪', 'herbis_ent_b2', '西'),
  // ==== 大阪駅前第3ビル B1F（公式マップ区画座標→3×3セル判定・全75店 2026-07） ====
  g('ホリーズカフェ', 'ekimae3_b1', '北西'),
  g('四文屋 大阪駅前第3ビル店', 'ekimae3_b1', '北西'),
  g('呑処 はせがわ', 'ekimae3_b1', '北西'),
  g('ワインとオマール海老の店 UOMO', 'ekimae3_b1', '北西'),
  g('どんがめ 大阪駅前第三ビル', 'ekimae3_b1', '北西'),
  g('第三宝島', 'ekimae3_b1', '北'),
  g('うどんと酒逢わせ めん次郎', 'ekimae3_b1', '北'),
  g('肉屋の串カツ 丸力', 'ekimae3_b1', '北'),
  g('エンジェルコンタクト', 'ekimae3_b1', '北'),
  g('串かつでんがな', 'ekimae3_b1', '北'),
  g('チケットジャパン第3ビル店', 'ekimae3_b1', '北'),
  g('キャビンリカー', 'ekimae3_b1', '北'),
  g('マキシ亭', 'ekimae3_b1', '北'),
  g('徳田酒店', 'ekimae3_b1', '北'),
  g('餃子の王将', 'ekimae3_b1', '北'),
  g('ダイヤモンドカリー', 'ekimae3_b1', '北'),
  g('大阪トンテキ', 'ekimae3_b1', '北'),
  g('大衆酒場 天神大ホール', 'ekimae3_b1', '北'),
  g('海藤花', 'ekimae3_b1', '北'),
  g('Men\'s Salon Chocolat 大阪駅前第3ビル', 'ekimae3_b1', '北'),
  g('女性美容師サロン Chocolat UMEDA', 'ekimae3_b1', '北'),
  g('ジャポニカ', 'ekimae3_b1', '北'),
  g('獄麺', 'ekimae3_b1', '北'),
  g('インド料理シュリアルナ 第3ビル店', 'ekimae3_b1', '北'),
  g('海鮮屋台 新鮮組', 'ekimae3_b1', '北'),
  g('囲炉裏屋 炭えん', 'ekimae3_b1', '北東'),
  g('ホリーズカフェ', 'ekimae3_b1', '北東'),
  g('フジオコーヒー', 'ekimae3_b1', '北東'),
  g('立ち呑み いなせや', 'ekimae3_b1', '北東'),
  g('鳥すけ', 'ekimae3_b1', '西'),
  g('(株)マルコ酒店', 'ekimae3_b1', '西'),
  g('花こよみ', 'ekimae3_b1', '西'),
  g('田ごと', 'ekimae3_b1', '西'),
  g('アメリカンバー1969', 'ekimae3_b1', '西'),
  g('大分からあげと鉄板焼 勝男', 'ekimae3_b1', '西'),
  g('大衆食堂 うめだホール', 'ekimae3_b1', '西'),
  g('居酒屋1969', 'ekimae3_b1', '西'),
  g('1969', 'ekimae3_b1', '西'),
  g('赤酢 謹賀', 'ekimae3_b1', '西'),
  g('花狩人・かとう', 'ekimae3_b1', '西'),
  g('IndianRestaurant Gautama', 'ekimae3_b1', '中央'),
  g('アラキ眼科', 'ekimae3_b1', '中央'),
  g('梅田産直市場', 'ekimae3_b1', '中央'),
  g('おでんと鴨蕎麦 居酒屋じんべえ', 'ekimae3_b1', '中央'),
  g('癒憩(yukai)第3ビル店', 'ekimae3_b1', '中央'),
  g('酒場 おか長', 'ekimae3_b1', '東'),
  g('ReCORE鍼灸接骨院 梅田', 'ekimae3_b1', '東'),
  g('大大阪', 'ekimae3_b1', '東'),
  g('リラクゼーション 健康園', 'ekimae3_b1', '東'),
  g('新世界 串カツ いっとく 大阪駅前第3ビル店', 'ekimae3_b1', '東'),
  g('セブン-イレブン大阪駅前第3ビル店', 'ekimae3_b1', '東'),
  g('活魚専門 隆勢丸', 'ekimae3_b1', '南西'),
  g('スタンド 1969', 'ekimae3_b1', '南西'),
  g('寿司鷹', 'ekimae3_b1', '南西'),
  g('カレントフーズ', 'ekimae3_b1', '南西'),
  g('麦酒&欧州バル グルメ異人館', 'ekimae3_b1', '南西'),
  g('最鳥 第3ビルB1店', 'ekimae3_b1', '南西'),
  g('大衆酒場びりちゃん2', 'ekimae3_b1', '南西'),
  g('シネマG', 'ekimae3_b1', '南西'),
  g('楠木フサエ おもや', 'ekimae3_b1', '南'),
  g('日本酒 かんき', 'ekimae3_b1', '南'),
  g('立呑み 晩杯屋 第3ビル', 'ekimae3_b1', '南'),
  g('串かつでんがな', 'ekimae3_b1', '南'),
  g('餃子エイト', 'ekimae3_b1', '南'),
  g('レストランOKINAWA', 'ekimae3_b1', '南'),
  g('田楽と季節料理おかじま', 'ekimae3_b1', '南'),
  g('大衆酒場 五の五', 'ekimae3_b1', '南'),
  g('徳田酒店 肉食専科', 'ekimae3_b1', '南'),
  g('ロイヤル', 'ekimae3_b1', '南東'),
  g('吉野家', 'ekimae3_b1', '南東'),
  g('堂山食堂', 'ekimae3_b1', '南東'),
  g('すし酒場 さしす', 'ekimae3_b1', '南東'),
  g('松乃家', 'ekimae3_b1', '南東'),
  g('つるや(株)大阪駅前店', 'ekimae3_b1', '南東'),
  g('金券ショップ アイギフト', 'ekimae3_b1', '南東'),
  // ==== 大阪駅前第3ビル B2F（公式マップ区画座標→3×3セル判定・全99店 2026-07） ====
  g('トクトクチケット', 'ekimae3_b2', '北西'),
  g('甲南チケット', 'ekimae3_b2', '北西'),
  g('ジッポーワールド ナカムラ', 'ekimae3_b2', '北西'),
  g('あかひげ薬局 大阪梅田店', 'ekimae3_b2', '北西'),
  g('酒場 おか長', 'ekimae3_b2', '北西'),
  g('珈琲店スパニョラ', 'ekimae3_b2', '北西'),
  g('鉄板焼肉・ホルモン まきの', 'ekimae3_b2', '北西'),
  g('大衆酒場 フレンチマン', 'ekimae3_b2', '北西'),
  g('K-kanギフト.com', 'ekimae3_b2', '北西'),
  g('ケーズ ファクトリー', 'ekimae3_b2', '北西'),
  g('焼売のジョー', 'ekimae3_b2', '北西'),
  g('すし酒場 さしす', 'ekimae3_b2', '北西'),
  g('中華料理 金の華', 'ekimae3_b2', '北西'),
  g('チケットキャビン 第3ビル店', 'ekimae3_b2', '北'),
  g('ゲオモバイル', 'ekimae3_b2', '北'),
  g('うる寅商店', 'ekimae3_b2', '北'),
  g('韓国料理 アリラン', 'ekimae3_b2', '北'),
  g('天ぷらとワイン大塩', 'ekimae3_b2', '北'),
  g('長屋オムライス 大阪駅前第3ビル店', 'ekimae3_b2', '北'),
  g('キラメキノ未来', 'ekimae3_b2', '北'),
  g('立ち呑み 庶民', 'ekimae3_b2', '北'),
  g('靴 シューギャラリー', 'ekimae3_b2', '北'),
  g('アメモバ梅田・大阪店', 'ekimae3_b2', '北'),
  g('かどや', 'ekimae3_b2', '北'),
  g('ロイヤルエイト', 'ekimae3_b2', '北'),
  g('元祖変わりかつ丼・親子丼専門店 祭太鼓', 'ekimae3_b2', '北'),
  g('ぶどう亭', 'ekimae3_b2', '北'),
  g('うどん棒 大阪本店', 'ekimae3_b2', '北'),
  g('第3ビルタイガー', 'ekimae3_b2', '北'),
  g('大衆酒場 スタンド マルカツ', 'ekimae3_b2', '北'),
  g('居酒屋 にゆう・とうきよう', 'ekimae3_b2', '北'),
  g('海鮮一番', 'ekimae3_b2', '北'),
  g('寿司屋 のだ', 'ekimae3_b2', '北'),
  g('炭火焼鳥 鶏えん', 'ekimae3_b2', '北'),
  g('ユタカヤ 時計宝飾', 'ekimae3_b2', '北東'),
  g('酒と宴H(昆布料理)', 'ekimae3_b2', '北東'),
  g('中国気功整体院(駅前第3ビル店)', 'ekimae3_b2', '北東'),
  g('Bonta', 'ekimae3_b2', '北東'),
  g('トライイット', 'ekimae3_b2', '北東'),
  g('(株)交通趣味ギャラリー', 'ekimae3_b2', '北東'),
  g('立ち呑みのくち', 'ekimae3_b2', '西'),
  g('らぁ麺もう利', 'ekimae3_b2', '西'),
  g('立呑み 焼きスパ ローマ軒', 'ekimae3_b2', '西'),
  g('イタリア食堂 cima', 'ekimae3_b2', '西'),
  g('笑福', 'ekimae3_b2', '西'),
  g('てんぷらや 夢二', 'ekimae3_b2', '西'),
  g('おでん ばる', 'ekimae3_b2', '西'),
  g('和歌山由良港地魚直送 昭和丸', 'ekimae3_b2', '西'),
  g('麟家厨房', 'ekimae3_b2', '西'),
  g('名物どてカツ どて煮込み 酒場おちょぼ', 'ekimae3_b2', '西'),
  g('梅田くだん', 'ekimae3_b2', '西'),
  g('チキンチキン', 'ekimae3_b2', '西'),
  g('オハコミート', 'ekimae3_b2', '西'),
  g('サイゼリヤ', 'ekimae3_b2', '西'),
  g('アールエイチワイ', 'ekimae3_b2', '中央'),
  g('ワンズゴルフアカデミー', 'ekimae3_b2', '中央'),
  g('梅亭 中華居酒屋', 'ekimae3_b2', '中央'),
  g('大分からあげと鉄板焼き 勝男B2応援団', 'ekimae3_b2', '中央'),
  g('カレー百貨・居酒屋・カレー夢', 'ekimae3_b2', '中央'),
  g('やまもと 梅田店', 'ekimae3_b2', '東'),
  g('カーニバルレコード', 'ekimae3_b2', '東'),
  g('バラエティ雑貨 ワッツ', 'ekimae3_b2', '東'),
  g('青空リラクゼーション', 'ekimae3_b2', '東'),
  g('占い館 アナスタシア', 'ekimae3_b2', '東'),
  g('占の城', 'ekimae3_b2', '東'),
  g('永井古書店', 'ekimae3_b2', '東'),
  g('HOLOS RELAXATION HOUSE', 'ekimae3_b2', '東'),
  g('まるかんの店 大阪駅前店', 'ekimae3_b2', '東'),
  g('CRYSTAL FUSION', 'ekimae3_b2', '東'),
  g('カットハウスJ(1000円カット専門店)', 'ekimae3_b2', '東'),
  g('ほしよみ堂 大阪梅田店', 'ekimae3_b2', '東'),
  g('ネスパ', 'ekimae3_b2', '南西'),
  g('大鳥印章', 'ekimae3_b2', '南西'),
  g('首コリほぐし梅田院', 'ekimae3_b2', '南西'),
  g('徳田酒店 第3ビルB2店', 'ekimae3_b2', '南西'),
  g('リラクゼーション〜カオリア〜', 'ekimae3_b2', '南西'),
  g('占いの館 キセキ', 'ekimae3_b2', '南西'),
  g('リラクゼーションサロン Calm', 'ekimae3_b2', '南西'),
  g('カレーハウスCoCo壱番屋', 'ekimae3_b2', '南'),
  g('王宮', 'ekimae3_b2', '南'),
  g('イタリアン バール ガルゴッタ', 'ekimae3_b2', '南'),
  g('酒蔵 呑', 'ekimae3_b2', '南'),
  g('RUDYS クラブデリシャス', 'ekimae3_b2', '南'),
  g('ファイテンショップ梅田店', 'ekimae3_b2', '南'),
  g('踊るうどん', 'ekimae3_b2', '南'),
  g('串焼きと鉄板一心', 'ekimae3_b2', '南'),
  g('串カツ 天満 七福神', 'ekimae3_b2', '南'),
  g('キリンケラー ヤマト', 'ekimae3_b2', '南'),
  g('中国料理 遙華', 'ekimae3_b2', '南'),
  g('RHY 音楽教室', 'ekimae3_b2', '南'),
  g('Calypso ネイルサロン', 'ekimae3_b2', '南'),
  g('ステーキファイブと寿司六', 'ekimae3_b2', '南東'),
  g('中華料理 金明飯店', 'ekimae3_b2', '南東'),
  g('ターリー屋', 'ekimae3_b2', '南東'),
  g('リラクゼーション Relieve', 'ekimae3_b2', '南東'),
  g('(株)八百富写眞機店 第3ビル店', 'ekimae3_b2', '南東'),
  g('琉球', 'ekimae3_b2', '南東'),
  g('サクセス', 'ekimae3_b2', '南東'),
  g('ダイコクドラッグ', 'ekimae3_b2', '南東'),
  // ==== 大阪駅前第4ビル B1F（公式マップ区画座標→3×3セル判定・全53店 2026-07） ====
  g('加藤気功療法 梅田院', 'ekimae4_b1', '北西'),
  g('HEALING(ヒーリング) リラクゼーション', 'ekimae4_b1', '北'),
  g('珈琲の辞書 第二章', 'ekimae4_b1', '北'),
  g('森宮リラクゼーション', 'ekimae4_b1', '北'),
  g('リラクゼーション cocosia', 'ekimae4_b1', '北'),
  g('玉椿', 'ekimae4_b1', '北'),
  g('PCコンフル梅田店', 'ekimae4_b1', '北東'),
  g('青空', 'ekimae4_b1', '北東'),
  g('Shaving Room esprit', 'ekimae4_b1', '西'),
  g('Sakura-blow 大阪駅前第4ビル店', 'ekimae4_b1', '西'),
  g('ライール ザ バーバー', 'ekimae4_b1', '西'),
  g('リラクゼーションサロン Relax', 'ekimae4_b1', '西'),
  g('JOUJOUセントラル', 'ekimae4_b1', '西'),
  g('Hair Room esprit', 'ekimae4_b1', '西'),
  g('カードショップ絆', 'ekimae4_b1', '西'),
  g('フットラボ インスティテュート', 'ekimae4_b1', '中央'),
  g('酒飲みよ大志を抱け', 'ekimae4_b1', '中央'),
  g('クリーンス', 'ekimae4_b1', '中央'),
  g('(株)ヴィーナストラベル', 'ekimae4_b1', '中央'),
  g('アジアンバルフロッグス', 'ekimae4_b1', '中央'),
  g('占いの館キセキ', 'ekimae4_b1', '中央'),
  g('ペペロンチーノ専門店 ぺろん', 'ekimae4_b1', '中央'),
  g('Lavender', 'ekimae4_b1', '中央'),
  g('(株)みずほ銀行', 'ekimae4_b1', '中央'),
  g('ヤナギ屋', 'ekimae4_b1', '中央'),
  g('大衆酒場 あかマル', 'ekimae4_b1', '東'),
  g('立呑み処 七津屋', 'ekimae4_b1', '東'),
  g('宝くじ売場((株)宝友)', 'ekimae4_b1', '東'),
  g('ラーメンステーション大阪駅前第4ビル', 'ekimae4_b1', '東'),
  g('GORON! 大阪第4ビル', 'ekimae4_b1', '東'),
  g('丸亀製麺', 'ekimae4_b1', '東'),
  g('GiGO 大阪第4ビル', 'ekimae4_b1', '東'),
  g('ゆりかご', 'ekimae4_b1', '南西'),
  g('The secondroom cafe', 'ekimae4_b1', '南西'),
  g('汁なし担担麺専門 キング軒', 'ekimae4_b1', '南西'),
  g('ヘッドスパ専門サロン スカルクイック大阪店', 'ekimae4_b1', '南西'),
  g('全力ストレッチ', 'ekimae4_b1', '南西'),
  g('iPhone修理救急便', 'ekimae4_b1', '南西'),
  g('きたがわ', 'ekimae4_b1', '南'),
  g('バールワン', 'ekimae4_b1', '南'),
  g('皆様酒場 昭和ゴールデン', 'ekimae4_b1', '南'),
  g('オステリアガウダンテ', 'ekimae4_b1', '南'),
  g('relaxation salon libres', 'ekimae4_b1', '南'),
  g('大富豪', 'ekimae4_b1', '南'),
  g('おしゃん亭', 'ekimae4_b1', '南'),
  g('立ち呑み 庶民', 'ekimae4_b1', '南'),
  g('たこ焼酒場しん家', 'ekimae4_b1', '南'),
  g('チケット キャビン', 'ekimae4_b1', '南東'),
  g('酒場リベリーニギる／大衆食堂ぬ', 'ekimae4_b1', '南東'),
  g('鉄板焼とおでん 小鉄', 'ekimae4_b1', '南東'),
  g('サカバダアレグロ', 'ekimae4_b1', '南東'),
  g('立呑み 晩杯屋', 'ekimae4_b1', '南東'),
  g('麺\'s room 神虎', 'ekimae4_b1', '南東'),
  // ==== 大阪駅前第4ビル B2F（公式マップ区画座標→3×3セル判定・全49店 2026-07） ====
  g('でんがな', 'ekimae4_b2', '北西'),
  g('徳田酒店第4ビルB2店', 'ekimae4_b2', '北'),
  g('韓国料理シンガネ', 'ekimae4_b2', '北'),
  g('レイク大阪第4ビル店((株)SBI新生銀行)', 'ekimae4_b2', '北'),
  g('欧風軒', 'ekimae4_b2', '北'),
  g('チケットジャパン 4ビル東店', 'ekimae4_b2', '北'),
  g('煮干しらーめん玉五郎', 'ekimae4_b2', '北'),
  g('おさかな屋オカピ', 'ekimae4_b2', '北東'),
  g('ひもの野郎', 'ekimae4_b2', '北東'),
  g('串カツ七福神', 'ekimae4_b2', '西'),
  g('喫茶 愛', 'ekimae4_b2', '西'),
  g('特製鯵フライと沖縄SOBAR がんじゅー', 'ekimae4_b2', '西'),
  g('大衆酒場フレンチマン 第4ビル店', 'ekimae4_b2', '西'),
  g('ローソン第4ビル地下2階', 'ekimae4_b2', '西'),
  g('占いの館キセキ', 'ekimae4_b2', '西'),
  g('マルリキ', 'ekimae4_b2', '西'),
  g('文の助茶屋梅田店', 'ekimae4_b2', '中央'),
  g('スワンナプームタイ', 'ekimae4_b2', '中央'),
  g('Bodysh', 'ekimae4_b2', '中央'),
  g('PINOT', 'ekimae4_b2', '中央'),
  g('喜蘭', 'ekimae4_b2', '中央'),
  g('快癒優', 'ekimae4_b2', '中央'),
  g('中国気功整体院 第四ビル2号店', 'ekimae4_b2', '中央'),
  g('立呑み処七津屋(はなれ)', 'ekimae4_b2', '中央'),
  g('Q-Bang! 4th東梅田店', 'ekimae4_b2', '中央'),
  g('THE CUT', 'ekimae4_b2', '中央'),
  g('クロスローズ・プランニング(株) Palette', 'ekimae4_b2', '東'),
  g('キリンケラーヤマト 東梅田店', 'ekimae4_b2', '東'),
  g('和み庵', 'ekimae4_b2', '東'),
  g('アコム(株)', 'ekimae4_b2', '東'),
  g('(株)大黒屋大阪駅前第四ビル店', 'ekimae4_b2', '東'),
  g('サンドラッグ 大阪駅前第4ビル地下2階店', 'ekimae4_b2', '東'),
  g('爽身閣', 'ekimae4_b2', '南西'),
  g('アイフル(株)', 'ekimae4_b2', '南西'),
  g('青空', 'ekimae4_b2', '南西'),
  g('石井歯科クリニック 梅田院', 'ekimae4_b2', '南西'),
  g('Bijoux Kique(ビジューキク)', 'ekimae4_b2', '南西'),
  g('くだものだもの', 'ekimae4_b2', '南西'),
  g('LuLuAs 第四ビル店', 'ekimae4_b2', '南西'),
  g('でんがな', 'ekimae4_b2', '南西'),
  g('予心 サロン', 'ekimae4_b2', '南西'),
  g('大衆酒場 第4ビルB2 タイガー', 'ekimae4_b2', '南'),
  g('勝男', 'ekimae4_b2', '南'),
  g('福嶋屋', 'ekimae4_b2', '南'),
  g('十八番', 'ekimae4_b2', '南'),
  g('花びし 和じあん 梅田店', 'ekimae4_b2', '南'),
  g('中国気功整体院', 'ekimae4_b2', '南'),
  g('ダイコクドラッグ第4ビル店', 'ekimae4_b2', '南東'),
  g('ファミリーマート大阪駅前第4ビル店', 'ekimae4_b2', '南東'),
  // ==== 大阪駅前第1ビル B1F（公式マップ・方位は大阪市資料と照合済み・全47店 2026-07） ====
  g('Q-Bang！3rd(パチンコ・スロット)', 'ekimae1_b1', '北西'),
  g('理容 ユイ', 'ekimae1_b1', '北西'),
  g('今井きしょう', 'ekimae1_b1', '北西'),
  g('うどん・そば・食事処 三起', 'ekimae1_b1', '北西'),
  g('ダイワンテレコム梅田店', 'ekimae1_b1', '北'),
  g('占い ここにいた', 'ekimae1_b1', '北'),
  g('塩ラーメン専門店 汐〇 -shiomaru-', 'ekimae1_b1', '北'),
  g('スパイスカレー Roche(ロシュ)', 'ekimae1_b1', '北'),
  g('サカバ第1', 'ekimae1_b1', '北'),
  g('リラクゼーション癒憩 第一ビル店', 'ekimae1_b1', '北'),
  g('OWL(アウル)クリニック', 'ekimae1_b1', '北東'),
  g('Indian Restaurant Khajuraho', 'ekimae1_b1', '北東'),
  g('ホリーズカフェ', 'ekimae1_b1', '北東'),
  g('良心的大衆酒場 鶴亀八番', 'ekimae1_b1', '北東'),
  g('ルーズベルトBeer食堂', 'ekimae1_b1', '北東'),
  g('海鮮串オカピ', 'ekimae1_b1', '北東'),
  g('衣料お直し屋さん 彩縫館', 'ekimae1_b1', '北'),
  g('ロシア料理 モスクワ プリュス シェミ', 'ekimae1_b1', '北'),
  g('リラクゼーション 憩〜IKOI〜', 'ekimae1_b1', '北'),
  g('喫茶 マヅラ', 'ekimae1_b1', '北'),
  g('シャーロックホームズ(英国パブ)', 'ekimae1_b1', '北'),
  g('マヅラ ジョニーウォーカー', 'ekimae1_b1', '中央'),
  g('買取本舗ドットコム梅田1号店', 'ekimae1_b1', '中央'),
  g('賢人-かしこびと-', 'ekimae1_b1', '中央'),
  g('Q-Bang！2nd(パチンコ・スロット)', 'ekimae1_b1', '西'),
  g('キング オブ キングス', 'ekimae1_b1', '南'),
  g('クラフトギャラリーOWL', 'ekimae1_b1', '南'),
  g('吉田眼科/アゲイン', 'ekimae1_b1', '南'),
  g('大和クラブ(麻雀)', 'ekimae1_b1', '南'),
  g('湯浅港', 'ekimae1_b1', '南'),
  g('もみほぐし堂', 'ekimae1_b1', '南'),
  g('癒しの空間 整体マッサージ 華', 'ekimae1_b1', '南'),
  g('TREVOR(ヘアーサロン)', 'ekimae1_b1', '南'),
  g('Peace(ピース)リラクゼーション', 'ekimae1_b1', '南'),
  g('オリエンタル鍼灸整骨院', 'ekimae1_b1', '南'),
  g('萬願亭', 'ekimae1_b1', '南'),
  g('RAPUR(ラピュール)', 'ekimae1_b1', '南西'),
  g('北野', 'ekimae1_b1', '南西'),
  g('スタンドカレー ワタナベ', 'ekimae1_b1', '南西'),
  g('ドトール', 'ekimae1_b1', '南西'),
  g('北北新地', 'ekimae1_b1', '南西'),
  g('Party Space Bar OPEN DOOR', 'ekimae1_b1', '南東'),
  g('TREVOR DERTISAN(美容室)', 'ekimae1_b1', '南東'),
  g('あすなろ書店', 'ekimae1_b1', '南東'),
  g('雲仙調理部', 'ekimae1_b1', '南東'),
  g('リラクゼーション ファイン', 'ekimae1_b1', '南東'),
  g('飯田鍼灸整骨院 リラクゼーションサロン シュシュ', 'ekimae1_b1', '南東'),
  // ==== 大阪駅前第1ビル B2F（公式マップ・方位は大阪市資料と照合済み・全77店 2026-07） ====
  g('大衆料理・居酒屋 御影郷 ふくじゅ', 'ekimae1_b2', '北西'),
  g('九州もん', 'ekimae1_b2', '北西'),
  g('鶏酒場 大阪梅田アイボリー', 'ekimae1_b2', '北西'),
  g('立ち呑み処 まる', 'ekimae1_b2', '北西'),
  g('リラクゼーション ファイン', 'ekimae1_b2', '北西'),
  g('(株)FIVE CRYSTAL', 'ekimae1_b2', '北東'),
  g('金券ショップ チケットスーパー', 'ekimae1_b2', '北東'),
  g('からだ接骨院', 'ekimae1_b2', '北東'),
  g('スマイルコンタクト', 'ekimae1_b2', '北東'),
  g('チケットキャビン第1ビル店', 'ekimae1_b2', '西'),
  g('チケット販売 第一ギフト', 'ekimae1_b2', '西'),
  g('呑み処リンゴ屋', 'ekimae1_b2', '西'),
  g('DUBSTA(ダブスタ)', 'ekimae1_b2', '西'),
  g('ファミリーマート+コクミンドラッグ', 'ekimae1_b2', '中央'),
  g('インド料理 ニルヴァーナ', 'ekimae1_b2', '中央'),
  g('立ち飲み処 和', 'ekimae1_b2', '中央'),
  g('幸せ立ち飲み 夢ごりら', 'ekimae1_b2', '中央'),
  g('うどん店 たかはた', 'ekimae1_b2', '中央'),
  g('酒処 あかね', 'ekimae1_b2', '中央'),
  g('スタンド割烹 若桜', 'ekimae1_b2', '中央'),
  g('寿司 まぐろ一徹', 'ekimae1_b2', '中央'),
  g('中華料理 金明飯店 3号店', 'ekimae1_b2', '中央'),
  g('らーめんやまちゃん イッちゃん', 'ekimae1_b2', '中央'),
  g('買取本舗ドットコム 梅田買取センター', 'ekimae1_b2', '東'),
  g('アーユル ヴェーダ ウイズ', 'ekimae1_b2', '東'),
  g('TEA ROOM 木馬', 'ekimae1_b2', '東'),
  g('SHB東洋医学総合センター', 'ekimae1_b2', '東'),
  g('CRAFT BEER BASE BUD', 'ekimae1_b2', '東'),
  g('バル ミトン', 'ekimae1_b2', '東'),
  g('丸喜酒店', 'ekimae1_b2', '東'),
  g('ひもの野郎', 'ekimae1_b2', '東'),
  g('LULUAS ルルアス(リラクゼーション)', 'ekimae1_b2', '東'),
  g('華神(カシン)', 'ekimae1_b2', '東'),
  g('シスターブラウン', 'ekimae1_b2', '東'),
  g('鞄ヤ 絆商事(株)', 'ekimae1_b2', '東'),
  g('呑み処 大阪梅田 ブラウン', 'ekimae1_b2', '東'),
  g('徳田酒店', 'ekimae1_b2', '南西'),
  g('酒菜や いしもん 西対', 'ekimae1_b2', '南西'),
  g('手打ちうどんの店 たかはた', 'ekimae1_b2', '南西'),
  g('たばこ(つるつる庵)', 'ekimae1_b2', '南西'),
  g('Q-Bang！1st(パチンコ・スロット)', 'ekimae1_b2', '南西'),
  g('屋台餃子', 'ekimae1_b2', '南西'),
  g('中国気功整体院(春風堂)', 'ekimae1_b2', '南西'),
  g('立呑パーラー 西澤商店', 'ekimae1_b2', '南西'),
  g('大衆酒場 マルリキ', 'ekimae1_b2', '南西'),
  g('CRAFTROOM(BAR)', 'ekimae1_b2', '南西'),
  g('鮪人 まぐろんちゅ', 'ekimae1_b2', '南西'),
  g('TAKOYAKI & BAR POULPE', 'ekimae1_b2', '南'),
  g('お酒の美術館', 'ekimae1_b2', '南'),
  g('夢ごりら', 'ekimae1_b2', '南'),
  g('カレーショップ ミクロ', 'ekimae1_b2', '南'),
  g('一二三堂(マッサージ)/梅田整骨院', 'ekimae1_b2', '南'),
  g('そば・うどん・めん処 つるつる庵', 'ekimae1_b2', '南'),
  g('彦寿司', 'ekimae1_b2', '南'),
  g('ちょっとした料理とおばんざい ふらん', 'ekimae1_b2', '南'),
  g('SALON de SUEHIRO', 'ekimae1_b2', '南'),
  g('銀座屋', 'ekimae1_b2', '南'),
  g('大衆酒場 酒房 吉豊', 'ekimae1_b2', '南'),
  g('喫茶・軽食 フルール', 'ekimae1_b2', '南'),
  g('花と緑 フラワーガーデン', 'ekimae1_b2', '南'),
  g('酒菜や いしもん 対屋', 'ekimae1_b2', '南'),
  g('立ち飲み 庶民', 'ekimae1_b2', '南'),
  g('お好み焼 とみや', 'ekimae1_b2', '南'),
  g('新世界串かつ いっとく 大阪駅前第1ビル店', 'ekimae1_b2', '南'),
  g('青空リラクゼーション', 'ekimae1_b2', '南'),
  g('愉快酒場', 'ekimae1_b2', '南'),
  g('GOLF SHOP ティーアップ', 'ekimae1_b2', '南'),
  g('酒菜や いしもん', 'ekimae1_b2', '南'),
  g('炉ばた焼季節料理 本安兵衛', 'ekimae1_b2', '南東'),
  g('スマイルハンド', 'ekimae1_b2', '南東'),
  g('spice32', 'ekimae1_b2', '南東'),
  g('商品券 梅田スタンプ', 'ekimae1_b2', '南東'),
  g('ミトン', 'ekimae1_b2', '南東'),
  g('DVD・ビデオ販売 エース', 'ekimae1_b2', '南東'),
  g('串揚げ たぬき', 'ekimae1_b2', '南東'),
  g('インド料理 ミラ', 'ekimae1_b2', '南東'),
  g('立ち飲みワイン 立ちぶどう千本', 'ekimae1_b2', '南東'),
  // ==== 大阪駅前第2ビル B1F（公式マップ・方位は大阪市資料と照合済み・全65店 2026-07） ====
  g('チャイニーズ酒家 豪華(フーバー)', 'ekimae2_b1', '北西'),
  g('福祉交換所', 'ekimae2_b1', '北西'),
  g('タイ古式マッサージ Jasminum ジャスミン', 'ekimae2_b1', '北西'),
  g('肉食系酒場 片岡肉じろう', 'ekimae2_b1', '北西'),
  g('リラクゼーション 癒し手', 'ekimae2_b1', '北西'),
  g('大衆酒場 台所や はなれ', 'ekimae2_b1', '北西'),
  g('肉汁餃子のダンダダン 大阪駅前第2ビル店', 'ekimae2_b1', '北西'),
  g('ひねり蛇口ハイ 大衆酒泉 テルマエ', 'ekimae2_b1', '北西'),
  g('台湾料理 味仙', 'ekimae2_b1', '北西'),
  g('K2クラフト 合鍵・靴修理', 'ekimae2_b1', '北西'),
  g('大衆飯店 十八番', 'ekimae2_b1', '北西'),
  g('北京整体院', 'ekimae2_b1', '北西'),
  g('立吞屋 楠木フサエ 本店', 'ekimae2_b1', '北西'),
  g('楠木フサエ はなれ', 'ekimae2_b1', '北西'),
  g('naa rak 整体院', 'ekimae2_b1', '北西'),
  g('トータルリラクゼーション 癒身園', 'ekimae2_b1', '北'),
  g('ちかごろのカレー屋さん カナエ', 'ekimae2_b1', '北'),
  g('堂山食堂', 'ekimae2_b1', '北'),
  g('大衆串カツ よっとこ', 'ekimae2_b1', '北'),
  g('爽＆快', 'ekimae2_b1', '北'),
  g('大衆酒場 台所や', 'ekimae2_b1', '北'),
  g('リラクゼーション 癒憩〜Yukai〜', 'ekimae2_b1', '北'),
  g('めん処 つるつる庵', 'ekimae2_b1', '北'),
  g('ステーキファイブと寿司六', 'ekimae2_b1', '北'),
  g('まじめや', 'ekimae2_b1', '北東'),
  g('セブンイレブン 大阪駅前第2ビル店B1', 'ekimae2_b1', '北東'),
  g('海鮮酒場 ナカヒデ', 'ekimae2_b1', '西'),
  g('タイ古式マッサージ ルアンタイ', 'ekimae2_b1', '西'),
  g('立吞処 しげ家', 'ekimae2_b1', '西'),
  g('カフェ・ラ・ネージュ', 'ekimae2_b1', '中央'),
  g('理容 Cut-A', 'ekimae2_b1', '中央'),
  g('吞み処 りんご屋 パート1', 'ekimae2_b1', '中央'),
  g('大富豪', 'ekimae2_b1', '東'),
  g('おたからや 梅田1丁目店', 'ekimae2_b1', '東'),
  g('Bar SECOND FILL', 'ekimae2_b1', '東'),
  g('串カツ わんさか', 'ekimae2_b1', '東'),
  g('カフェ＆スタンド エルソル', 'ekimae2_b1', '東'),
  g('HYデンタルクリニック', 'ekimae2_b1', '東'),
  g('KAOLIA〜カオリア〜', 'ekimae2_b1', '東'),
  g('トータルバランスover', 'ekimae2_b1', '東'),
  g('パチンコ LUXOR', 'ekimae2_b1', '南西'),
  g('スロット RUSH', 'ekimae2_b1', '南西'),
  g('インド家庭料理 マハラジャ', 'ekimae2_b1', '南西'),
  g('すし 魚貴', 'ekimae2_b1', '南西'),
  g('TAMANE', 'ekimae2_b1', '南西'),
  g('吞み処 りんご屋 パート2', 'ekimae2_b1', '南西'),
  g('555 BOUTIQUE スリーファイブ', 'ekimae2_b1', '南西'),
  g('居酒屋 味善', 'ekimae2_b1', '南西'),
  g('AsianBody リラクゼーション', 'ekimae2_b1', '南西'),
  g('ハンヤ印章店', 'ekimae2_b1', '南西'),
  g('大衆酒場 どんがめ', 'ekimae2_b1', '南'),
  g('どんがめ まっくす 大阪駅前第2ビル店', 'ekimae2_b1', '南'),
  g('餃子のかっちゃん', 'ekimae2_b1', '南'),
  g('立食焼肉 一穂 第2ビル店', 'ekimae2_b1', '南'),
  g('大衆吞処 サカグラ', 'ekimae2_b1', '南'),
  g('鉄板串酒場 しん家', 'ekimae2_b1', '南'),
  g('がってん 大阪駅前第2ビル店', 'ekimae2_b1', '南東'),
  g('まきし亭本店', 'ekimae2_b1', '南東'),
  g('大衆焼肉・ホルモン よっとこ', 'ekimae2_b1', '南東'),
  g('元祖 Mr.鶏っく', 'ekimae2_b1', '南東'),
  g('梅田大衆酒場 H', 'ekimae2_b1', '南東'),
  g('大衆酒肴スタンド さかば。', 'ekimae2_b1', '南東'),
  g('大分からあげと鉄板焼き 勝男 B1応援団', 'ekimae2_b1', '南東'),
  g('肴屋 あしか', 'ekimae2_b1', '南東'),
  g('おでんとお蕎麦 居酒屋 じんべえ', 'ekimae2_b1', '南東'),
  // ==== 大阪駅前第2ビル B2F（公式マップ・方位は大阪市資料と照合済み・全93店 2026-07） ====
  g('お酒買取販売専門店 キャビンリカー', 'ekimae2_b2', '北西'),
  g('(株)チケットゾーン', 'ekimae2_b2', '北西'),
  g('モスバーガー 大阪駅前第2ビル店', 'ekimae2_b2', '北西'),
  g('コーヒー＆バー パイルドライバー', 'ekimae2_b2', '北西'),
  g('チケットキャビン 梅田本部', 'ekimae2_b2', '北西'),
  g('アクセスチケット 大阪2ビル店', 'ekimae2_b2', '北西'),
  g('横浜家系ラーメン 梅田屋', 'ekimae2_b2', '北西'),
  g('スマイルハンド 第2ビル店', 'ekimae2_b2', '北西'),
  g('ダイコクドラッグ 大阪駅前NEW第2ビル店', 'ekimae2_b2', '北西'),
  g('整体×骨盤 カラダファクトリー', 'ekimae2_b2', '北西'),
  g('リラクゼーションサロン Riche(リッシュ)', 'ekimae2_b2', '北西'),
  g('頭で刈る頭 理容 ユイ', 'ekimae2_b2', '北西'),
  g('(株)甲南チケット 大阪駅前第2ビル店', 'ekimae2_b2', '北'),
  g('ゴールドチケット 梅田店', 'ekimae2_b2', '北'),
  g('チケットラボ', 'ekimae2_b2', '北'),
  g('さぬきうどん 四国屋', 'ekimae2_b2', '北'),
  g('チャーシューエッグ ポルコ食堂', 'ekimae2_b2', '北'),
  g('水産卸売直営酒処 花神 2ビル市場', 'ekimae2_b2', '北'),
  g('半立ちダイニングバー MIYA', 'ekimae2_b2', '北'),
  g('チケットジャパン 第2ビル店', 'ekimae2_b2', '北'),
  g('立呑み 梅田 パープル', 'ekimae2_b2', '北'),
  g('つけ麺 紋次郎', 'ekimae2_b2', '北'),
  g('ジョニーのからあげ 大阪駅前第2ビル店', 'ekimae2_b2', '北'),
  g('sou & kai', 'ekimae2_b2', '北'),
  g('天神大ホール 第2ビル店', 'ekimae2_b2', '北'),
  g('チケットキャビン 東店', 'ekimae2_b2', '北東'),
  g('立吞み処 七津屋', 'ekimae2_b2', '北東'),
  g('中国気功整体院 5号店', 'ekimae2_b2', '北東'),
  g('Relaxation Sabaidee サバイディ', 'ekimae2_b2', '北東'),
  g('豚々亭', 'ekimae2_b2', '北東'),
  g('2ビルのいしもん', 'ekimae2_b2', '北東'),
  g('ワイン＆洋風お好み焼き アベロ食堂', 'ekimae2_b2', '北東'),
  g('立ち吞み みねこ', 'ekimae2_b2', '西'),
  g('レンタルボックス＆チケット CABIN', 'ekimae2_b2', '西'),
  g('串カツ でんがな', 'ekimae2_b2', '西'),
  g('ちるり 盛岡冷麺・タンしゃぶ', 'ekimae2_b2', '西'),
  g('リラクゼーション 癒楽整体院', 'ekimae2_b2', '西'),
  g('WCB UMEDA 1', 'ekimae2_b2', '西'),
  g('磯丸水産 大阪駅前第2ビル店', 'ekimae2_b2', '西'),
  g('すし酒場 さしす', 'ekimae2_b2', '中央'),
  g('餃子の王将', 'ekimae2_b2', '中央'),
  g('アリラン(韓国家庭料理)', 'ekimae2_b2', '東'),
  g('熊本馬刺鶏料理の遊食家 アズバード', 'ekimae2_b2', '東'),
  g('焼鳥 牛たん どんたく', 'ekimae2_b2', '東'),
  g('にしき', 'ekimae2_b2', '東'),
  g('占いの館 キセキ 大阪駅前第2ビル中央店', 'ekimae2_b2', '東'),
  g('中国気功整体院', 'ekimae2_b2', '東'),
  g('オットモンテ', 'ekimae2_b2', '東'),
  g('らーめん やまちゃん', 'ekimae2_b2', '東'),
  g('喫茶 ジャマイカ', 'ekimae2_b2', '東'),
  g('大阪駅前第2ビル内 郵便局', 'ekimae2_b2', '東'),
  g('大衆すし 謹賀', 'ekimae2_b2', '南西'),
  g('お立吞み処 たよし 大阪駅前第2ビル店', 'ekimae2_b2', '南西'),
  g('紳士・婦人靴 トキワ商会', 'ekimae2_b2', '南西'),
  g('コーヒーハウス イフ', 'ekimae2_b2', '南西'),
  g('大衆居酒屋 黒たぬき', 'ekimae2_b2', '南西'),
  g('肉屋の串カツ 丸力 大阪駅前第2ビル店', 'ekimae2_b2', '南西'),
  g('大阪駅前第2ビルB2 応援団 勝男', 'ekimae2_b2', '南西'),
  g('SAKE and FOOD ボクのスタンド', 'ekimae2_b2', '南西'),
  g('金明飯店', 'ekimae2_b2', '南西'),
  g('至極の麺 華', 'ekimae2_b2', '南西'),
  g('ホルモン焼 おかだ', 'ekimae2_b2', '南西'),
  g('北京飯店', 'ekimae2_b2', '南西'),
  g('cafe & bar for you II', 'ekimae2_b2', '南西'),
  g('シャトレーヌ・プラス', 'ekimae2_b2', '南西'),
  g('立ち吞み まさ 梅田店', 'ekimae2_b2', '南'),
  g('Caffe MINIMO', 'ekimae2_b2', '南'),
  g('うどん・そば 麺2', 'ekimae2_b2', '南'),
  g('居食や きんやま', 'ekimae2_b2', '南'),
  g('買取りまっくす B2店', 'ekimae2_b2', '南'),
  g('居酒屋 柚', 'ekimae2_b2', '南'),
  g('JAZZ & BAR ホワッツ・ニユー', 'ekimae2_b2', '南'),
  g('らーめん チョンマゲ 梅田店', 'ekimae2_b2', '南'),
  g('変わりかつ丼 祭太鼓', 'ekimae2_b2', '南'),
  g('リラクゼーションサロン エリート', 'ekimae2_b2', '南'),
  g('Little Bar リトルバー', 'ekimae2_b2', '南東'),
  g('居酒屋 平田', 'ekimae2_b2', '南東'),
  g('ビリヤニ HUB', 'ekimae2_b2', '南東'),
  g('タチノミエイト 第2ビル店', 'ekimae2_b2', '南東'),
  g('大衆居酒屋 よっとこ', 'ekimae2_b2', '南東'),
  g('焼鳥 にのや', 'ekimae2_b2', '南東'),
  g('ちゃんこ居酒屋 太一山', 'ekimae2_b2', '南東'),
  g('麺屋7.5Hz+ 梅田店', 'ekimae2_b2', '南東'),
  g('エラワン タイ式マッサージ', 'ekimae2_b2', '南東'),
  g('田中表具店 掛軸茶屋', 'ekimae2_b2', '南東'),
  g('占いの館 キセキ 第2ビル店', 'ekimae2_b2', '南東'),
  g('フラワーショップ 花次郎', 'ekimae2_b2', '南東'),
  g('立ち吞み 庶民', 'ekimae2_b2', '南東'),
  g('ギャラリー39', 'ekimae2_b2', '南東'),
  g('フランス風一膳飯屋＆ワイン彩々 いわむら', 'ekimae2_b2', '南東'),
  g('スキルワン 大阪梅田店', 'ekimae2_b2', '南東'),
  g('占いの館 anastasia アナスタシア', 'ekimae2_b2', '南東'),
  g('つけ麺専門 虎ノ王', 'ekimae2_b2', '南東'),
  // ==== LINKS UMEDA B1F(オイシイもの横丁・LINKS MARCHE他)（公式マップ・方位確認済み・全36店 2026-07） ====
  g('ニューすしセンター200', 'links_b1', '北東'),
  g('うまいもん酒場 源喜', 'links_b1', '北東'),
  g('海鮮と串焼きのお店 鈴音', 'links_b1', '北'),
  g('焼肉ジャパン', 'links_b1', '北東'),
  g('HUB', 'links_b1', '北東'),
  g('博多ぐるぐるとりかわ 竹乃屋', 'links_b1', '北東'),
  g('もつ焼 もつ福', 'links_b1', '北東'),
  g('金の粉', 'links_b1', '北東'),
  g('BAR ESPAÑOL PEQUEÑO', 'links_b1', '北東'),
  g('焼鳥ボトルバード', 'links_b1', '北東'),
  g('ODD', 'links_b1', '北東'),
  g('たこ酒場 くれおーる', 'links_b1', '北東'),
  g('肉処 大阪ブラウン', 'links_b1', '北東'),
  g('堂山食堂', 'links_b1', '北東'),
  g('漁師酒場あらき', 'links_b1', '東'),
  g('函館立喰い寿司 函太郎', 'links_b1', '東'),
  g('梅田のしんちゃん', 'links_b1', '東'),
  g('大衆中華酒場 若林', 'links_b1', '東'),
  g('桐麺', 'links_b1', '東'),
  g('福岡鮮魚卸直営店 ビストロ酒場 ウオスケ', 'links_b1', '東'),
  g('スーパーマーケット Harves', 'links_b1', '北西'),
  g('マクドナルド', 'links_b1', '北西'),
  g('みどりの雑貨屋', 'links_b1', '北'),
  g('さち福やCAFÉ', 'links_b1', '北'),
  g('開運館E&E', 'links_b1', '北'),
  g('わしたショップ', 'links_b1', '北'),
  g('スギ薬局', 'links_b1', '北'),
  g('韓time', 'links_b1', '北'),
  g('お酒の美術館', 'links_b1', '北'),
  g('クリスピー・クリーム・ドーナツ', 'links_b1', '北東'),
  g('ゴンチャ', 'links_b1', '東'),
  g('SUBWAY', 'links_b1', '東'),
  g('スターバックス コーヒー', 'links_b1', '東'),
  g('青山フラワーマーケット', 'links_b1', '東'),
  g('Apple Shop', 'links_b1', '中央'),
  g('ヨドバシカメラ マルチメディア梅田 B1売場', 'links_b1', '南'),
  // ==== 阪神梅田本店B1F スナックパーク（公式マップ・方位確認済み・全14店 2026-07） ====
  g('阪神ビールスタンド', 'snackpark', '北西'),
  g('えきそば', 'snackpark', '北'),
  g('ふじたま', 'snackpark', '中央'),
  g('たまご丸', 'snackpark', '北'),
  g('カドヤ食堂', 'snackpark', '北'),
  g('大阪本場 中央市場 藤味', 'snackpark', '中央'),
  g('うまかラーメン', 'snackpark', '東'),
  g('天ぷらの山', 'snackpark', '東'),
  g('阪神名物 いか焼き', 'snackpark', '南東'),
  g('ローマ軒', 'snackpark', '西'),
  g('寿司 魚がし日本一', 'snackpark', '南西'),
  g('海鮮丼の駅前', 'snackpark', '中央'),
  g('元祖ちょぼ焼き本舗', 'snackpark', '南'),
  g('お好み焼き おフクさん', 'snackpark', '南'),
  // ==== KITTE大阪B1F うめよこ（公式マップ・方位確認済み・全26店 2026-07） ====
  g('角打ち 小野の離れ', 'umeyoko', '北西'),
  g('コロッセオ バル', 'umeyoko', '北西'),
  g('壱岐島', 'umeyoko', '西'),
  g('水炊きおでん ヤマニ', 'umeyoko', '西'),
  g('大旦那', 'umeyoko', '西'),
  g('Luv.Fish？大阪', 'umeyoko', '南西'),
  g('たこ焼き発祥の店 大阪玉出 会津屋', 'umeyoko', '南西'),
  g('BLARNEY IRISH PUB & CAFÉ', 'umeyoko', '西'),
  g('仙台牛たん串 きぐし', 'umeyoko', '西'),
  g('すし酒場さしす', 'umeyoko', '中央'),
  g('舎鈴', 'umeyoko', '中央'),
  g('ニカイノオアシス', 'umeyoko', '中央'),
  g('川北商店', 'umeyoko', '西'),
  g('肉と魚がうまい酒場ニューツルマツ', 'umeyoko', '西'),
  g('中華バルサワダ', 'umeyoko', '北西'),
  g('串カツ・発酵おばんざい 揚八', 'umeyoko', '北西'),
  g('フレッシュネスバーガー', 'umeyoko', '南'),
  g('absinthe org.Salad&Grill', 'umeyoko', '中央'),
  g('ポーたま', 'umeyoko', '中央'),
  g('CRISP SALAD WORKS', 'umeyoko', '北'),
  g('MILK DO dore iku?', 'umeyoko', '北'),
  g('デリカキッチン', 'umeyoko', '北'),
  g('ファミリーマート', 'umeyoko', '東'),
  g('ミルク＆パフェ よつ葉ホワイトコージ', 'umeyoko', '東'),
  g('スギ薬局', 'umeyoko', '東'),
  g('タリーズコーヒー', 'umeyoko', '南東'),
  // ==== イーマ E-MA（公式サイトフロアガイド・全32店 2026-07。地下接続はB1のみ→全館1点集約） ====
  // B2F
  g('スターバックス コーヒー 梅田イーマ店', 'ema_all', '中央'),
  g('MIO CLINIC', 'ema_all', '中央'),
  g('HIROGINZA BARBER SHOP 大阪本店', 'ema_all', '中央'),
  g('select SIMイーマ梅田店', 'ema_all', '中央'),
  g('スマプロ 梅田店', 'ema_all', '中央'),
  // B1F
  g('café & books bibliothéque', 'ema_all', '中央'),
  g("LOFTMANCOOP / LOFTMANCOOP 'Ohana", 'ema_all', '中央'),
  g('G.B. Gafas', 'ema_all', '中央'),
  g('投資信託相談プラザ 梅田イーマ店', 'ema_all', '中央'),
  g('ゴッド ラッシュ大阪駅前梅田イーマ店', 'ema_all', '中央'),
  g('着物レンタルVASARA大阪梅田店', 'ema_all', '中央'),
  // 1F
  g('ストレスレス ショールーム大阪', 'ema_all', '中央'),
  g('EXクリニック 大阪梅田院', 'ema_all', '中央'),
  // 2F
  g('オープンハウス 梅田営業センター', 'ema_all', '中央'),
  g('オープンハウス・アーキテクト LIFE DESIGN PARK', 'ema_all', '中央'),
  // 3F
  g('オキュロフェイシャルクリニック大阪', 'ema_all', '中央'),
  g('ビーウェイブ', 'ema_all', '中央'),
  g('梅田E-MA川崎クリニック', 'ema_all', '中央'),
  g('エミナルクリニック梅田院', 'ema_all', '中央'),
  // 4F
  g('Qilt+LIM', 'ema_all', '中央'),
  g('atelier+LIM', 'ema_all', '中央'),
  g('même+LIM', 'ema_all', '中央'),
  g('LIM NAIL SCHOOL', 'ema_all', '中央'),
  g('トキコクリニック梅田院', 'ema_all', '中央'),
  g('大阪ブレストクリニック 梅田イーマ', 'ema_all', '中央'),
  // 5F
  g('但馬屋', 'ema_all', '中央'),
  g('カッシーワ', 'ema_all', '中央'),
  g('ONEPERSON 梅田', 'ema_all', '中央'),
  g('大阪梅田さいとう矯正歯科', 'ema_all', '中央'),
  // 6F
  g('カトレア歯科・美容クリニック', 'ema_all', '中央'),
  g('馬渕教室 東進衛星予備校', 'ema_all', '中央'),
  g('メンズエミナル', 'ema_all', '中央'),
  // ==== うめきた広場B1F UMEKITA CELLAR（公式マップ・方位確認済み・全18店 2026-07） ====
  g('おにぎりこんが', 'umekita_cellar', '中央'),
  g('Umi&Yama Kitchen', 'umekita_cellar', '中央'),
  g('PIENO di PASTA', 'umekita_cellar', '北東'),
  g('❛OHANABATAKE', 'umekita_cellar', '北東'),
  g('河内鴨 蕎麦 スタンド 藤乃', 'umekita_cellar', '北'),
  g('おかゆと麺 粥餐庁', 'umekita_cellar', '北西'),
  g('芋屋金次郎', 'umekita_cellar', '南西'),
  g('24/7 cafe apartment', 'umekita_cellar', '西'),
  g('春水堂', 'umekita_cellar', '東'),
  g('BAR & GELATERIA RAFFINATO', 'umekita_cellar', '東'),
  g('CRÊPERIE Le Beurre Noisette', 'umekita_cellar', '中央'),
  g('DEAN & DELUCA', 'umekita_cellar', '北'),
  g('茅乃舎', 'umekita_cellar', '南西'),
  g('mango tree kitchen "khao man gai"', 'umekita_cellar', '北'),
  g('FamilyMart', 'umekita_cellar', '南'),
  g('ワインショップ・エノテカ', 'umekita_cellar', '北西'),
  g('THE CITY BAKERY', 'umekita_cellar', '南西'),
  g('Natural House Aoyama Organicmart', 'umekita_cellar', '西'),
];
